<?php declare(strict_types=1);$filters=$reporting['filters'];$catalogue=$reporting['catalogue'];$metrics=$reporting['metrics'];$summary=$metrics['summary'];$query=http_build_query($filters->query());$statuses=[''=>'All statuses','active'=>'Active','lapsed'=>'Lapsed','submitted'=>'Submitted','under_review'=>'Under review','query_raised'=>'Query raised','approved'=>'Approved','rejected'=>'Rejected','enrolled'=>'Enrolled','completed'=>'Completed','withdrawn'=>'Withdrawn','registered'=>'Registered','attended'=>'Attended','cancelled'=>'Cancelled','pending'=>'Pending','successful'=>'Successful','failed'=>'Failed']; ?>
<section class="section"><div class="container-wide">
<div class="section-heading"><p class="eyebrow">Restricted administration</p><h1>Reporting dashboard</h1><p>Current membership position and bounded activity metrics for <?= $e($filters->from) ?> to <?= $e($filters->to) ?>.</p></div>
<form method="get" action="/admin/reports" class="form-grid admin-panel" aria-label="Report filters">
<label>From<input type="date" name="from" value="<?= $e($filters->from) ?>" required></label><label>To<input type="date" name="to" value="<?= $e($filters->to) ?>" required></label>
<label>Membership grade<select name="membership_grade"><option value="">All grades</option><?php foreach($catalogue['membership_grades'] as$item):?><option value="<?= $e($item['public_id']) ?>" <?= $filters->membershipGrade===$item['public_id']?'selected':'' ?>><?= $e($item['name']) ?></option><?php endforeach;?></select></label>
<label>Programme<select name="programme"><option value="">All programmes</option><?php foreach($catalogue['programmes'] as$item):?><option value="<?= $e($item['public_id']) ?>" <?= $filters->programme===$item['public_id']?'selected':'' ?>><?= $e($item['code'].' — '.$item['name']) ?></option><?php endforeach;?></select></label>
<label>Professional area<select name="professional_area"><option value="">All areas</option><?php foreach($catalogue['professional_areas'] as$item):?><option value="<?= $e($item['public_id']) ?>" <?= $filters->professionalArea===$item['public_id']?'selected':'' ?>><?= $e($item['name']) ?></option><?php endforeach;?></select></label>
<label>Event<select name="event"><option value="">All events</option><?php foreach($catalogue['events'] as$item):?><option value="<?= $e($item['public_id']) ?>" <?= $filters->event===$item['public_id']?'selected':'' ?>><?= $e($item['title'].' — '.$item['event_date']) ?></option><?php endforeach;?></select></label>
<label>Status<select name="status"><?php foreach($statuses as$value=>$label):?><option value="<?= $e($value) ?>" <?= $filters->status===$value?'selected':'' ?>><?= $e($label) ?></option><?php endforeach;?></select></label><button class="btn btn-navy" type="submit">Apply filters</button>
</form>
<div class="card-grid" aria-label="Report metrics"><?php foreach(['total_members'=>'Total members','active_members'=>'Active members','membership_applications'=>'Membership applications','pending_reviews'=>'Pending reviews','renewals_due'=>'Renewals due','programme_applications'=>'Programme applications','programme_enrolments'=>'Programme enrolments','event_registrations'=>'Event registrations']as$key=>$label):?><article class="feature-card"><p class="eyebrow"><?= $e($label) ?></p><h2><?= number_format((int)$summary[$key]) ?></h2></article><?php endforeach;?><?php if($metrics['finance']!==null):?><article class="feature-card"><p class="eyebrow">Verified payments</p><h2><?= number_format((int)$metrics['finance']['payments']) ?></h2></article><article class="feature-card"><p class="eyebrow">Verified revenue</p><h2><?= $e(($metrics['finance']['currency']??'').' '.number_format(((int)$metrics['finance']['revenue_minor'])/100,2)) ?></h2></article><?php endif;?></div>
<div class="admin-list"><section class="admin-panel"><h2>Members by grade</h2><div class="table-responsive" role="region" aria-label="Members by grade table" tabindex="0"><table class="table"><thead><tr><th>Grade</th><th>Total</th><th>Active</th></tr></thead><tbody><?php foreach($metrics['members_by_grade']as$row):?><tr><td><?= $e($row['label']) ?></td><td><?= number_format((int)$row['total']) ?></td><td><?= number_format((int)$row['active']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($metrics['finance']!==null):?><section class="admin-panel"><h2>Revenue by category</h2><div class="table-responsive" role="region" aria-label="Revenue by category table" tabindex="0"><table class="table"><thead><tr><th>Category</th><th>Currency</th><th>Invoices</th><th>Revenue</th></tr></thead><tbody><?php foreach($metrics['finance']['by_category']as$row):?><tr><td><?= $e(ucwords(str_replace('_',' ',$row['category']))) ?></td><td><?= $e($row['currency']) ?></td><td><?= number_format((int)$row['invoices']) ?></td><td><?= number_format(((int)$row['revenue_minor'])/100,2) ?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?></div>
<?php if($reporting['can_export']):?><section class="admin-panel"><h2>CSV exports</h2><p>Exports contain at most 10,000 rows and use the selected date range and applicable filters.</p><div class="cta-row"><?php foreach(['members'=>'Members','membership_applications'=>'Membership applications','programme_applications'=>'Programme applications','programme_enrolments'=>'Programme enrolments','event_registrations'=>'Event registrations']as$type=>$label):?><a class="btn btn-outline-navy" href="/admin/reports/export?report=<?= $e($type) ?>&amp;<?= $e($query) ?>"><?= $e($label) ?></a><?php endforeach;?><?php if($reporting['can_finance']):?><a class="btn btn-outline-navy" href="/admin/reports/export?report=payments&amp;<?= $e($query) ?>">Payments</a><?php endif;?></div></section><?php endif;?>
</div></section>
