<?php

declare(strict_types=1);

namespace App\Services\Cms;

use App\Authorization\PermissionCheckerInterface;use App\Security\SafeHtml;use DateTimeImmutable;use DomainException;use RuntimeException;
final class CmsService
{
 public function __construct(private readonly CmsRepositoryInterface$repository,private readonly PermissionCheckerInterface$permissions,private readonly SafeHtml$html,private readonly CmsMediaStorage$storage){}
 public function posts(string$type):array{try{return in_array($type,['news','announcement','resource'],true)?$this->repository->publicPosts($type):[];}catch(\Throwable){return[];}}public function post(string$type,string$slug):?array{try{return$this->slugValid($slug)&&in_array($type,['news','announcement','resource'],true)?$this->repository->publicPost($type,$slug):null;}catch(\Throwable){return null;}}public function page(string$slug):?array{try{return$this->slugValid($slug)?$this->repository->publicPage($slug):null;}catch(\Throwable){return null;}}public function library():array{try{return$this->repository->publicLibrary();}catch(\Throwable){return['resources'=>[],'downloads'=>[],'faqs'=>[]];}}
 public function media(string$id):?array{try{return$this->uuid($id)?$this->repository->publicMedia($id):null;}catch(\Throwable){return null;}}public function download(string$slug):?array{try{return$this->slugValid($slug)?$this->repository->publicDownload($slug,new DateTimeImmutable('now')):null;}catch(\Throwable){return null;}}public function readMedia(array$media):string{return$this->storage->read((string)$media['storage_path']);}
 public function admin(int$actor):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to manage website content.');return CmsResult::success('CMS loaded.',$this->repository->adminDashboard());}
 public function savePage(int$actor,?string$id,array$input):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to edit pages.');$common=$this->content($actor,$id,$input);if($common instanceof CmsResult)return$common;try{return CmsResult::success('Page saved.',['public_id'=>$this->repository->savePage($actor,$id,$common,new DateTimeImmutable('now'))]);}catch(DomainException$e){return CmsResult::failure(409,$e->getMessage());}}
 public function savePost(int$actor,?string$id,array$input):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to edit posts.');$type=$this->text($input,'post_type');if(!in_array($type,['news','announcement','resource'],true))return CmsResult::failure(422,'Post type is invalid.');$common=$this->content($actor,$id,$input);if($common instanceof CmsResult)return$common;$common['post_type']=$type;$common['excerpt']=$this->limited($input,'excerpt',500);try{return CmsResult::success('Post saved.',['public_id'=>$this->repository->savePost($actor,$id,$common,new DateTimeImmutable('now'))]);}catch(DomainException$e){return CmsResult::failure(409,$e->getMessage());}}
 public function saveFaq(int$actor,?string$id,array$input):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to edit FAQs.');$status=$this->status($actor,$input);$question=$this->text($input,'question');$answer=$this->text($input,'answer');$order=filter_var($input['display_order']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>65535]]);if($status===null||mb_strlen($question)<5||mb_strlen($question)>500||mb_strlen($answer)<2||mb_strlen($answer)>10000||$order===false)return CmsResult::failure(422,'Review the FAQ fields.');try{return CmsResult::success('FAQ saved.',['public_id'=>$this->repository->saveFaq($actor,$id,['question'=>$question,'answer_text'=>$answer,'display_order'=>$order,'status'=>$status],new DateTimeImmutable('now'))]);}catch(DomainException$e){return CmsResult::failure(409,$e->getMessage());}}
 public function upload(int$actor,array$file,array$input):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to upload media.');$stored=null;try{$stored=$this->storage->store($file);$stored['alt_text']=$this->limited($input,'alt_text',255);$stored['status']='draft';$stored['public_id']=$this->repository->createMedia($actor,$stored,new DateTimeImmutable('now'));return CmsResult::success('Media uploaded as a draft.',$stored);}catch(RuntimeException|DomainException$e){if(is_array($stored)&&isset($stored['storage_path']))$this->storage->delete((string)$stored['storage_path']);return CmsResult::failure(422,$e->getMessage());}}
 public function mediaStatus(int$actor,string$id,array$input):CmsResult{if(!$this->edit($actor)||!$this->uuid($id))return CmsResult::failure(403,'You are not authorized to update media.');$status=$this->status($actor,$input);if($status===null)return CmsResult::failure(422,'Media status is invalid or publishing is not authorized.');try{$this->repository->updateMediaStatus($actor,$id,$status,new DateTimeImmutable('now'));return CmsResult::success('Media status updated.');}catch(DomainException$e){return CmsResult::failure(409,$e->getMessage());}}
 public function saveDownload(int$actor,?string$id,array$input):CmsResult{if(!$this->edit($actor))return CmsResult::failure(403,'You are not authorized to edit downloads.');$status=$this->status($actor,$input);$title=$this->text($input,'title');$media=$this->text($input,'media');if($status===null||mb_strlen($title)<3||mb_strlen($title)>220||!$this->uuid($media))return CmsResult::failure(422,'Review the download fields.');try{return CmsResult::success('Download saved.',['public_id'=>$this->repository->saveDownload($actor,$id,['title'=>$title,'slug'=>$this->slug($title),'description'=>$this->limited($input,'description',1000),'media'=>$media,'status'=>$status],new DateTimeImmutable('now'))]);}catch(DomainException$e){return CmsResult::failure(409,$e->getMessage());}}
 private function content(int$actor,?string$id,array$input):array|CmsResult{if($id!==null&&!$this->uuid($id))return CmsResult::failure(404,'Content record not found.');$title=$this->text($input,'title');$status=$this->status($actor,$input);$body=is_string($input['body_html']??null)?$this->html->sanitize($input['body_html']):'';if(mb_strlen($title)<3||mb_strlen($title)>220||$status===null||$body===''||mb_strlen($body)>200000)return CmsResult::failure(422,'Review the content title, body, and status.');return['title'=>$title,'slug'=>$this->slug($title),'summary'=>$this->limited($input,'summary',500),'body_html'=>$body,'meta_title'=>$this->limited($input,'meta_title',255),'meta_description'=>$this->limited($input,'meta_description',500),'status'=>$status];}
 private function status(int$actor,array$i):?string{$s=$this->text($i,'status');if(!in_array($s,['draft','published','archived'],true))return null;if($s==='published'&&!$this->permissions->allows($actor,'cms.publish'))return null;return$s;}private function edit(int$a):bool{return$a>0&&$this->permissions->allows($a,'cms.edit');}private function text(array$i,string$k):string{return is_string($i[$k]??null)?trim($i[$k]):'';}private function limited(array$i,string$k,int$m):?string{$v=$this->text($i,$k);return$v===''?null:mb_substr($v,0,$m);}private function slug(string$v):string{$slug=trim(strtolower(preg_replace('/[^a-z0-9]+/i','-',$v)??''),'-');return substr($slug?:'content',0,200);}private function slugValid(string$v):bool{return preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/D',$v)===1;}private function uuid(string$v):bool{return preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/Di',$v)===1;}
}
