<?php declare(strict_types=1);
namespace App\Services\Events;
use App\Authorization\PermissionCheckerInterface;use App\Logging\Logger;use DateTimeImmutable;use DomainException;use Throwable;
final class EventService {
    public function __construct(private readonly EventRepositoryInterface $repository,private readonly PermissionCheckerInterface $permissions,private readonly ?Logger $logger=null){}
    public function directory():array{try{return ['available'=>true,'events'=>array_map(fn(array$event):array=>$this->safePublicEvent($event),$this->repository->publicEvents())];}catch(Throwable $e){$this->logger?->error('Event directory is unavailable.',['exception'=>$e]);return ['available'=>false,'events'=>[]];}} public function event(string $slug):?array{if(preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/D',$slug)!==1)return null;try{$event=$this->repository->publicEvent($slug);return is_array($event)?$this->safePublicEvent($event):null;}catch(Throwable $e){$this->logger?->error('Event detail is unavailable.',['exception'=>$e]);return null;}} public function memberRegistrations(int $user):array{return $user>0?$this->repository->memberRegistrations($user):[];}
    public function register(?int $user,string $eventId,array $input):EventResult{
        if(!$this->uuid($eventId))return EventResult::failure(404,'Event not found.');$name=$this->text($input,'name');$email=strtolower($this->text($input,'email'));$phone=$this->text($input,'phone');
        if(mb_strlen($name)<2||mb_strlen($name)>200)return EventResult::failure(422,'Enter the registrant name.');if($user===null&&filter_var($email,FILTER_VALIDATE_EMAIL)===false)return EventResult::failure(422,'Enter a valid email address.');if(mb_strlen($phone)>40)return EventResult::failure(422,'The phone number is too long.');
        try{$reference='EVT-'.date('Y').'-'.strtoupper(bin2hex(random_bytes(6)));return EventResult::success('Event registration completed.',$this->repository->register($user,$eventId,['name'=>$name,'email'=>$email,'phone'=>$phone?:null],$reference,new DateTimeImmutable('now')));}catch(DomainException $e){return EventResult::failure(409,$e->getMessage());}
    }
    public function adminDashboard(int $actor):EventResult{if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to manage events.');return EventResult::success('Events loaded.',$this->repository->adminDashboard());}
    public function attendees(int $actor,string $event):EventResult{if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to manage attendees.');if(!$this->uuid($event))return EventResult::failure(404,'Event not found.');$data=$this->repository->attendees($event);return $data?EventResult::success('Attendees loaded.',$data):EventResult::failure(404,'Event not found.');}
    public function saveEvent(int $actor,?string $id,array $input):EventResult{
        if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to save events.');if($id!==null&&!$this->uuid($id))return EventResult::failure(404,'Event not found.');
        $title=$this->text($input,'title');$type=$this->text($input,'event_type');$date=$this->date($input['event_date']??null);$start=$this->time($input['start_time']??null);$end=$this->time($input['end_time']??null);$deadline=$this->dateTime($input['registration_deadline']??null);$status=$this->text($input,'status');$access=$this->text($input,'registration_access');$errors=[];
        if(mb_strlen($title)<3||mb_strlen($title)>220)$errors[]='Event title must be between 3 and 220 characters.';if(!$this->uuid($type))$errors[]='Select a valid event type.';if($date===null)$errors[]='Enter a valid event date.';if(($input['start_time']??'')!==''&&$start===null||($input['end_time']??'')!==''&&$end===null||($start&&$end&&$end<=$start))$errors[]='Event times are invalid.';if(($input['registration_deadline']??'')!==''&&$deadline===null)$errors[]='Registration deadline is invalid.';if(!in_array($status,['draft','published','cancelled','completed'],true))$errors[]='Event status is invalid.';if(!in_array($access,['public','member'],true))$errors[]='Registration access is invalid.';if(mb_strlen($this->text($input,'venue'))>300)$errors[]='Venue must not exceed 300 characters.';
        $capacity=trim((string)($input['capacity']??''));$capacity=$capacity===''?null:filter_var($capacity,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($capacity===false)$errors[]='Capacity must be a positive whole number.';$fee=trim((string)($input['fee']??''));$fee=$fee===''?null:(is_numeric($fee)&&(float)$fee>=0?number_format((float)$fee,2,'.',''):false);if($fee===false)$errors[]='Fee must be a non-negative amount.';$currency=strtoupper($this->text($input,'fee_currency'));if($fee!==null&&preg_match('/^[A-Z]{3}$/D',$currency)!==1)$errors[]='A three-letter currency is required when a fee is supplied.';$url=$this->text($input,'online_url');if($url!==''&&(!$this->https($url)))$errors[]='Online URL must be a valid HTTPS address.';$banner=$this->text($input,'banner_path');if($banner!==''&&preg_match('#^/assets/uploads/events/[A-Za-z0-9/_-]+\.(?:jpe?g|png|webp)$#D',$banner)!==1)$errors[]='Banner path must reference a validated event image.';if(mb_strlen($this->text($input,'description'))>20000||mb_strlen($this->text($input,'eligibility'))>10000)$errors[]='Event description or eligibility information is too long.';if($errors)return EventResult::failure(422,implode(' ',$errors));
        try{$publicId=$this->repository->saveEvent($actor,$id,['event_type'=>$type,'title'=>$title,'slug'=>$this->slug($title),'description'=>$this->nullable($input,'description'),'event_date'=>$date,'start_time'=>$start,'end_time'=>$end,'venue'=>$this->nullable($input,'venue'),'online_url'=>$url?:null,'registration_deadline'=>$deadline,'capacity'=>$capacity,'fee'=>$fee,'fee_currency'=>$fee===null?null:$currency,'eligibility'=>$this->nullable($input,'eligibility'),'registration_access'=>$access,'banner_path'=>$banner?:null,'status'=>$status]);return EventResult::success($id===null?'Event created.':'Event updated.',['public_id'=>$publicId]);}catch(DomainException $e){return EventResult::failure(409,$e->getMessage());}
    }
    public function cancelEvent(int $actor,string $id):EventResult{return $this->adminVoid($actor,$id,fn()=> $this->repository->cancelEvent($actor,$id,new DateTimeImmutable('now')),'Event cancelled.');}
    public function cancelRegistration(int $actor,string $eventId,string $registrationId):EventResult{if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to manage events.');if(!$this->uuid($eventId)||!$this->uuid($registrationId))return EventResult::failure(404,'Registration not found.');try{$this->repository->cancelRegistration($actor,$eventId,$registrationId,new DateTimeImmutable('now'));return EventResult::success('Registration cancelled.');}catch(DomainException $e){return EventResult::failure(409,$e->getMessage());}}
    public function attend(int $actor,string $eventId,string $registrationId):EventResult{if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to record attendance.');if(!$this->uuid($eventId)||!$this->uuid($registrationId))return EventResult::failure(404,'Registration not found.');try{return EventResult::success('Attendance recorded.',$this->repository->recordAttendance($actor,$eventId,$registrationId,new DateTimeImmutable('now')));}catch(DomainException $e){return EventResult::failure(409,$e->getMessage());}}
    private function adminVoid(int $actor,string $id,callable $action,string $message):EventResult{if(!$this->admin($actor))return EventResult::failure(403,'You are not authorized to manage events.');if(!$this->uuid($id))return EventResult::failure(404,'Record not found.');try{$action();return EventResult::success($message);}catch(DomainException $e){return EventResult::failure(409,$e->getMessage());}}
    private function safePublicEvent(array$event):array{$banner=is_string($event['banner_path']??null)?trim($event['banner_path']):'';$event['banner_path']=preg_match('#^/assets/uploads/events/[A-Za-z0-9/_-]+\.(?:jpe?g|png|webp)$#D',$banner)===1&&!str_contains(rawurldecode($banner),'..')?$banner:null;$url=is_string($event['online_url']??null)?trim($event['online_url']):'';$event['online_url']=$url!==''&&$this->https($url)?$url:null;return$event;}private function admin(int $actor):bool{return $actor>0&&$this->permissions->allows($actor,'event.manage');}private function uuid(string $id):bool{return preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/Di',$id)===1;}private function text(array $in,string $key):string{return is_string($in[$key]??null)?trim($in[$key]):'';}private function nullable(array $in,string $key):?string{$v=$this->text($in,$key);return $v===''?null:$v;}private function slug(string $v):string{return trim(strtolower(preg_replace('/[^a-z0-9]+/i','-',$v)??''),'-');}private function date(mixed $v):?string{$v=is_string($v)?trim($v):'';$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);return$d&&$d->format('Y-m-d')===$v?$v:null;}private function time(mixed $v):?string{$v=is_string($v)?trim($v):'';if($v==='')return null;$d=DateTimeImmutable::createFromFormat('!H:i',$v);return$d&&$d->format('H:i')===$v?$v.':00':null;}private function dateTime(mixed $v):?string{$v=is_string($v)?trim($v):'';if($v==='')return null;$d=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$v);return$d&&$d->format('Y-m-d\TH:i')===$v?$d->format('Y-m-d H:i:s'):null;}private function https(string $url):bool{return filter_var($url,FILTER_VALIDATE_URL)!==false&&strtolower((string)parse_url($url,PHP_URL_SCHEME))==='https';}
}
