<?php declare(strict_types=1); echo $view->render('components.page-hero', compact('page', 'e')); $money = static fn (mixed $amount, mixed $currency): string => $amount === null || $amount === '' ? 'Not published' : $e((string) $currency . ' ' . number_format((float) $amount, 2)); ?>
<section class="section"><div class="container-narrow"><div class="programme-detail-grid">
<div class="prose"><p class="eyebrow"><?= $e($programme['type']['name']) ?> · <?= $e($programme['code']) ?></p><h2>Programme overview</h2><p><?= nl2br($e($programme['description'] ?: 'A full programme description has not yet been published.')) ?></p></div>
<dl class="detail-list"><div><dt>Duration</dt><dd><?= $e($programme['duration'] ?: 'Not published') ?></dd></div><div><dt>Delivery mode</dt><dd><?= $e($programme['delivery_mode'] ?: 'Not published') ?></dd></div><div><dt>Application fee</dt><dd><?= $money($programme['application_fee'], $programme['fee_currency']) ?></dd></div><div><dt>Tuition fee</dt><dd><?= $money($programme['tuition_fee'], $programme['fee_currency']) ?></dd></div></dl></div>
<div class="prose"><h2>Entry requirements</h2><p><?= nl2br($e($programme['entry_requirements'] ?: 'Entry requirements have not yet been published.')) ?></p></div>
<?php if ($programme['areas'] !== []): ?><div class="prose"><h2>Professional areas</h2><p><?php foreach ($programme['areas'] as $index => $area): ?><?= $index ? ', ' : '' ?><a href="/professional-areas/<?= rawurlencode($area['slug']) ?>"><?= $e($area['name']) ?></a><?php endforeach; ?></p></div><?php endif; ?>
<?php if ($programme['coordinators'] !== []): ?><div class="prose"><h2>Programme coordinators</h2><ul><?php foreach ($programme['coordinators'] as $person): ?><li><?= $e(trim(($person['title'] ? $person['title'] . ' ' : '') . $person['name'])) ?><?= $person['role'] ? ' — ' . $e($person['role']) : '' ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<div class="section-action"><a class="btn btn-navy" href="/account/programme-applications">Apply for a programme</a></div>
</div></section>
