<?php

declare(strict_types=1);

use App\Authorization\PermissionCheckerInterface;
use App\Services\Renewals\MembershipRenewalService;
use App\Services\Renewals\RenewalRepositoryInterface;

require dirname(__DIR__).'/vendor/autoload.php';
$assert=static function(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);};
try{
    $renewalId='10000000-0000-4000-8000-000000000001';$invoiceId='20000000-0000-4000-8000-000000000001';
    $repo=new class implements RenewalRepositoryInterface{public int$user=0;public int$verified=0;public int$overrides=0;public int$policies=0;public function dashboardForUser(int$userId):array{$this->user=$userId;return['member'=>['public_id'=>'member'],'policy'=>['period_value'=>18,'period_unit'=>'months'],'renewal'=>null];}public function generateForUser(int$userId,DateTimeImmutable$now):array{$this->user=$userId;return['renewal'=>['status'=>'payment_pending']];}public function applyVerifiedInvoice(string$invoicePublicId,DateTimeImmutable$now):void{$this->verified++;}public function expireDue(DateTimeImmutable$now):int{return 2;}public function adminRenewals():array{return[];}public function renewalConfiguration():array{return['grades'=>[],'fees'=>[],'policies'=>[]];}public function savePolicy(int$actorUserId,?string$policyPublicId,array$policy,DateTimeImmutable$now):string{$this->policies++;return'30000000-0000-4000-8000-000000000001';}public function override(int$actorUserId,string$renewalPublicId,string$action,string$reason,DateTimeImmutable$now):array{$this->overrides++;return['status'=>$action==='renew'?'renewed':'expired'];}};
    $denied=new class implements PermissionCheckerInterface{public function allows(int$userId,string$permission):bool{return false;}};$service=new MembershipRenewalService($repo,$denied);$dashboard=$service->dashboard(44);$assert($dashboard->successful&&$repo->user===44,'Renewal dashboard did not enforce authenticated ownership.');$assert($service->generate(44)->successful&&$repo->user===44,'Renewal invoice generation failed.');$service->paymentVerified($invoiceId);$assert($repo->verified===1,'Verified payment did not reach renewal reconciliation.');$assert($service->override(44,$renewalId,['action'=>'renew','reason'=>'Approved exception reason'])->status===403&&$repo->overrides===0,'Unauthorized override reached persistence.');
    $allowed=new class implements PermissionCheckerInterface{public function allows(int$userId,string$permission):bool{return$userId===9&&in_array($permission,['member.renewal_override','member.renewal_policy'],true);}};$service=new MembershipRenewalService($repo,$allowed);$assert($service->override(9,$renewalId,['action'=>'renew','reason'=>'Approved documented exception'])->successful&&$repo->overrides===1,'Authorized audited override failed.');$assert($service->override(9,$renewalId,['action'=>'expire','reason'=>'short'])->status===422,'Override without adequate reason was accepted.');$policy=$service->savePolicy(9,null,['name'=>'Flexible policy','membership_grade'=>'40000000-0000-4000-8000-000000000001','fee_setting'=>'50000000-0000-4000-8000-000000000001','period_value'=>'18','period_unit'=>'months','start_rule'=>'payment_date','renewal_window_days'=>'45','grace_days'=>'30','effective_from'=>'2026-01-01','effective_until'=>'2027-12-31','active'=>'1']);$assert($policy->successful&&$repo->policies===1,'Authorized configurable renewal policy failed.');$assert($service->expireDue()===2,'Configured expiry reconciliation hook failed.');
    $migration=(string)file_get_contents(dirname(__DIR__).'/database/migrations/20260905_240000_create_membership_renewal_tables.php');foreach(['CREATE TABLE membership_renewal_policies','CREATE TABLE membership_renewals','CREATE TABLE membership_renewal_history',"period_unit IN ('days','months','years')","start_rule IN ('current_expiry','payment_date')","'renewal_due','invoice_generated','payment_pending','paid','renewed','expired'",'fee_amount_minor BIGINT UNSIGNED','override_reason','ENGINE=InnoDB']as$n)$assert(str_contains($migration,$n),"Renewal migration missing {$n}.");
    $code=(string)file_get_contents(dirname(__DIR__).'/app/Repositories/MembershipRenewalRepository.php');foreach(['FOR UPDATE',"payments.status='successful'",'payments.verified_at IS NOT NULL','payments.amount_minor=invoices.total_minor','verified_payment','membership.renewal_admin_override','membership_renewal_history','transaction(function']as$n)$assert(str_contains($code,$n),"Renewal safety control missing {$n}.");$paymentCode=(string)file_get_contents(dirname(__DIR__).'/app/Services/Payments/PaymentService.php');$assert(str_contains($paymentCode,'verifiedPaymentListener?->paymentVerified'),'Renewal is not connected to verified payment settlement.');$seed=(string)file_get_contents(dirname(__DIR__).'/database/seeders/20260904_161000_rbac_seeder.php');$assert(str_contains($seed,'member.renewal_override')&&str_contains($seed,'member.renewal_policy'),'Renewal permissions missing.');
    echo"Membership renewal checks passed: configurable policies, owned invoice generation, verified-payment-only renewal, history, expiry hooks, RBAC override, and audit controls.\n";
}catch(Throwable$e){fwrite(STDERR,'Membership renewal check failed: '.$e->getMessage().PHP_EOL);exit(1);}
