define ROOT "C:/Ampps/www/aims/public"
define SITE "aims.test"

<VirtualHost *:80>
    ServerName ${SITE}
    ServerAlias *.${SITE}
    Redirect permanent / https://${SITE}/
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}

    <Directory "${ROOT}">
        Options -Indexes
        AllowOverride All
        Require all granted
    </Directory>

    SSLEngine on
    SSLCertificateFile "C:/laragon/etc/ssl/laragon.crt"
    SSLCertificateKeyFile "C:/laragon/etc/ssl/laragon.key"
</VirtualHost>
