<?php declare(strict_types=1);
namespace App\Controllers\Events;
use App\Controllers\Controller;use App\Http\Request;use App\Http\Response;use App\Security\Csrf;use App\Security\Security;use App\Security\SessionManager;use App\Services\Events\EventResult;use App\Services\Events\EventService;use App\Services\PublicSite\PublicContent;use App\View\View;
final class EventController extends Controller{
 public function __construct(View$v,Csrf$c,private readonly EventService$service,private readonly SessionManager$session,private readonly PublicContent$content){parent::__construct($v,$c);}
 public function index(Request$r):Response{$directory=$this->service->directory();return$this->render('events.index',$r,$this->content->page('events'),['events'=>$directory['events'],'directoryAvailable'=>$directory['available']]);}
 public function show(Request$r):Response{$event=$this->service->event((string)$r->route('event',''));if(!$event)return Response::html('<h1>404 Not Found</h1>',404);$page=['title'=>$event['title'],'meta_title'=>$event['title'].' | AIMS Nigeria','description'=>$event['description']?:'A professional event from AIMS Nigeria.','eyebrow'=>$event['type_name'],'heading'=>$event['title'],'summary'=>$event['description']?:'Verified event information.'];return$this->render('events.show',$r,$page,['event'=>$event,'message'=>$this->session->pullFlash('event_message'),'error'=>$this->session->pullFlash('event_error')]);}
 public function publicRegister(Request$r):Response{$slug=$r->input('event_slug');$destination=is_string($slug)&&preg_match('/^[a-z0-9-]+$/D',$slug)===1?'/events/'.rawurlencode($slug):'/events';return$this->registration($r,$this->service->register(null,(string)$r->route('event',''),$r->all()),$destination);}
 public function memberIndex(Request$r):Response{$slug=$r->input('event_slug');$event=is_string($slug)?$this->service->event($slug):null;$eventId=$r->input('event');if(!is_string($eventId)||!is_array($event)||($event['public_id']??null)!==$eventId)$event=null;return$this->render('events.member',$r,['title'=>'My event registrations','meta_title'=>'My Event Registrations | AIMS Nigeria','description'=>'Your professional event registrations.','robots'=>'noindex, nofollow'],['selectedEvent'=>$event,'registrations'=>$this->service->memberRegistrations($this->actor($r)),'message'=>$this->session->pullFlash('event_message'),'error'=>$this->session->pullFlash('event_error')]);}
 public function memberRegister(Request$r):Response{return$this->registration($r,$this->service->register($this->actor($r),(string)$r->route('event',''),$r->all()),'/account/event-registrations');}
 private function registration(Request$r,EventResult$result,string$destination):Response{$this->session->flash($result->successful?'event_message':'event_error',$result->message);return$this->redirect($destination)->withHeader('Cache-Control','no-store, private');}
 private function render(string$template,Request$r,array$page,array$data):Response{return$this->view($template,array_merge(['site'=>$this->content->site(),'navigation'=>$this->content->navigation(),'page'=>$page,'activePage'=>'events','requestPath'=>$r->path(),'e'=>[Security::class,'escape']],$data),'layouts.public')->withHeader('Cache-Control','no-store');}private function actor(Request$r):int{$u=$r->attribute('auth.user');return is_array($u)?(int)($u['id']??0):0;}
}
