<?php declare(strict_types=1);
namespace App\Controllers\Events;
use App\Controllers\Controller;use App\Http\Request;use App\Http\Response;use App\Security\Csrf;use App\Security\Security;use App\Security\SessionManager;use App\Services\Events\EventResult;use App\Services\Events\EventService;use App\Services\PublicSite\PublicContent;use App\View\View;
final class EventAdminController extends Controller{
 public function __construct(View$v,Csrf$c,private readonly EventService$service,private readonly SessionManager$session,private readonly PublicContent$content){parent::__construct($v,$c);}
 public function index(Request$r):Response{$result=$this->service->adminDashboard($this->actor($r));if(!$result->successful)return$this->error($result);return$this->render('event-admin.index','Event administration',$r,['catalogue'=>$result->data,'message'=>$this->session->pullFlash('event_admin_message'),'error'=>$this->session->pullFlash('event_admin_error')]);}
 public function attendees(Request$r):Response{$result=$this->service->attendees($this->actor($r),(string)$r->route('event',''));if(!$result->successful)return$this->error($result);return$this->render('event-admin.attendees','Event attendees',$r,['attendance'=>$result->data,'message'=>$this->session->pullFlash('event_admin_message'),'error'=>$this->session->pullFlash('event_admin_error')]);}
 public function create(Request$r):Response{return$this->action($this->service->saveEvent($this->actor($r),null,$r->all()),'/admin/events');}public function update(Request$r):Response{return$this->action($this->service->saveEvent($this->actor($r),(string)$r->route('event',''),$r->all()),'/admin/events');}public function cancel(Request$r):Response{return$this->action($this->service->cancelEvent($this->actor($r),(string)$r->route('event','')),'/admin/events');}public function cancelRegistration(Request$r):Response{$event=(string)$r->route('event','');return$this->action($this->service->cancelRegistration($this->actor($r),$event,(string)$r->route('registration','')),'/admin/events/'.rawurlencode($event).'/attendees');}public function attend(Request$r):Response{$event=(string)$r->route('event','');return$this->action($this->service->attend($this->actor($r),$event,(string)$r->route('registration','')),'/admin/events/'.rawurlencode($event).'/attendees');}
 private function action(EventResult$result,string$to):Response{$this->session->flash($result->successful?'event_admin_message':'event_admin_error',$result->message);return$this->redirect($to)->withHeader('Cache-Control','no-store, private');}private function render(string$template,string$title,Request$r,array$data):Response{return$this->view($template,array_merge(['site'=>$this->content->site(),'navigation'=>$this->content->navigation(),'page'=>['title'=>$title,'meta_title'=>$title.' | AIMS Nigeria','description'=>'Authorized event administration.','robots'=>'noindex, nofollow'],'activePage'=>'admin','requestPath'=>$r->path(),'e'=>[Security::class,'escape']],$data),'layouts.public')->withHeader('Cache-Control','no-store, private');}private function error(EventResult$r):Response{return Response::html($r->status===403?'<h1>403 Forbidden</h1>':'<h1>404 Not Found</h1>',$r->status===403?403:404);}private function actor(Request$r):int{$u=$r->attribute('auth.user');return is_array($u)?(int)($u['id']??0):0;}
}
