<?php

declare(strict_types=1);

namespace App\Controllers\MemberPortal;

use App\Controllers\Controller;
use App\Http\Request;
use App\Http\Response;
use App\Security\Csrf;
use App\Security\Security;
use App\Security\SessionManager;
use App\Services\MemberPortal\MemberPortalResult;
use App\Services\MemberPortal\MemberPortalService;
use App\Services\PublicSite\PublicContent;
use App\View\View;

final class MemberPortalController extends Controller
{
    private const SECTIONS = [
        'membership' => ['Membership', 'Your verified membership details and renewal status.', 'Membership records are read-only in the member portal. Contact authorized membership administration if a correction is required.'],
        'payments' => ['Payments', 'Invoices and payment history will appear here.', 'Payment processing is not enabled at this stage. This page is a safe integration hook only.'],
        'programmes' => ['Programmes', 'Your professional programme enrolments.', 'Use the programme application workspace to apply for published programmes or review your application status.'],
        'events' => ['Events', 'Your active professional event registrations.', 'Browse published events or open your event registration workspace.'],
        'certificates' => ['Certificates', 'Your issued certificates will appear here.', 'Certificate issuance and verification remain separate authorized workflows.'],
        'downloads' => ['Downloads', 'Your approved member downloads will appear here.', 'No member-specific downloads are currently published.'],
        'notifications' => ['Notifications', 'Your recent account notifications.', 'Notifications generated by future modules will be shown here.'],
        'security' => ['Security', 'Manage the security of your account.', 'Password recovery and secure session controls remain available through the authenticated account foundation.'],
        'support' => ['Support', 'Get help with your membership account.', 'Verified support contact channels will be connected when formally configured.'],
    ];

    public function __construct(
        View $view,
        Csrf $csrf,
        private readonly MemberPortalService $portal,
        private readonly SessionManager $session,
        private readonly PublicContent $content,
    ) {
        parent::__construct($view, $csrf);
    }

    public function dashboard(Request $request): Response
    {
        return $this->portalView('member-portal.dashboard', 'Member dashboard', 'dashboard', $request, [
            'portal' => $this->portalData($request),
            'message' => $this->session->pullFlash('member_portal_message'),
            'error' => $this->session->pullFlash('member_portal_error'),
        ]);
    }

    public function profile(Request $request): Response
    {
        return $this->portalView('member-portal.profile', 'My profile', 'profile', $request, [
            'portal' => $this->portalData($request),
            'message' => $this->session->pullFlash('member_portal_message'),
            'error' => $this->session->pullFlash('member_portal_error'),
            'errors' => [],
            'old' => [],
        ]);
    }

    public function updateProfile(Request $request): Response
    {
        $result = $this->portal->updateProfile($this->userId($request), $request->all());
        if ($result->successful) {
            $this->session->flash('member_portal_message', $result->message);

            return $this->redirect('/portal/profile')->withHeader('Cache-Control', 'no-store, private');
        }
        if ($result->status === 403) {
            return Response::html('<h1>403 Forbidden</h1>', 403)->withHeader('Cache-Control', 'no-store, private');
        }

        return $this->portalView('member-portal.profile', 'My profile', 'profile', $request, [
            'portal' => $this->portalData($request),
            'message' => null,
            'error' => $result->message,
            'errors' => $result->errors,
            'old' => $request->all(),
        ], 422);
    }

    public function section(Request $request): Response
    {
        $key = (string) $request->route('section', '');
        if (!isset(self::SECTIONS[$key])) {
            return Response::html('<h1>404 Not Found</h1>', 404);
        }
        [$title, $description, $notice] = self::SECTIONS[$key];

        return $this->portalView('member-portal.section', $title, $key, $request, [
            'portal' => $this->portalData($request),
            'sectionTitle' => $title,
            'sectionDescription' => $description,
            'sectionNotice' => $notice,
        ]);
    }

    /** @param array<string, mixed> $data */
    private function portalView(string $template, string $title, string $activeSection, Request $request, array $data, int $status = 200): Response
    {
        return $this->view($template, array_merge([
            'site' => $this->content->site(),
            'navigation' => $this->content->navigation(),
            'page' => [
                'title' => $title,
                'meta_title' => $title . ' | AIMS Nigeria',
                'description' => 'Secure AIMS Nigeria member portal.',
                'robots' => 'noindex, nofollow',
            ],
            'activePage' => 'member-portal',
            'activeSection' => $activeSection,
            'requestPath' => $request->path(),
            'e' => [Security::class, 'escape'],
        ], $data), 'layouts.public', $status)
            ->withHeader('Cache-Control', 'no-store, private')
            ->withHeader('Referrer-Policy', 'no-referrer');
    }

    /** @return array<string, mixed> */
    private function portalData(Request $request): array
    {
        $portal = $request->attribute('member.portal');

        return is_array($portal) ? $portal : [];
    }

    private function userId(Request $request): int
    {
        $user = $request->attribute('auth.user');

        return is_array($user) ? (int) ($user['id'] ?? 0) : 0;
    }
}
