<?php

declare(strict_types=1);

return [
    'site' => [
        'name' => 'Association for Information and Management Sciences, Nigeria',
        'short_name' => 'AIMS Nigeria',
        'description' => 'A professional digital platform for AIMS Nigeria membership, programmes, events, resources and verification services.',
        'official_email' => $environment->get('AIMS_OFFICIAL_EMAIL', ''),
        'membership_email' => $environment->get('AIMS_MEMBERSHIP_EMAIL', ''),
        'phone' => $environment->get('AIMS_PHONE', ''),
        'whatsapp' => $environment->get('AIMS_WHATSAPP', ''),
        'address' => $environment->get('AIMS_ADDRESS', ''),
        'website' => $environment->get('APP_URL', ''),
    ],
    'navigation' => [
        ['label' => 'Home', 'path' => '/'],
        ['label' => 'About', 'path' => '/about'],
        ['label' => 'Membership', 'path' => '/membership'],
        ['label' => 'Programmes', 'path' => '/programmes'],
        ['label' => 'Professional Areas', 'path' => '/professional-areas'],
        ['label' => 'Leadership', 'path' => '/leadership'],
        ['label' => 'Events', 'path' => '/events'],
        ['label' => 'Resources', 'path' => '/resources'],
        ['label' => 'News', 'path' => '/news'],
        ['label' => 'Contact', 'path' => '/contact'],
    ],
    'pages' => [
        'home' => [
            'title' => 'AIMS Nigeria',
            'meta_title' => 'AIMS Nigeria | Professional Association Platform',
            'description' => 'Discover AIMS Nigeria membership, professional programmes, areas of practice, events, resources and verification services.',
            'eyebrow' => 'Professional knowledge. Responsible practice.',
            'heading' => 'A professional platform built for credible growth.',
            'summary' => 'Explore the association, professional pathways and public services being brought together in one secure digital experience.',
        ],
        'about' => [
            'title' => 'About AIMS Nigeria',
            'description' => 'Learn about the Association for Information and Management Sciences, Nigeria and the structure of its digital platform.',
            'eyebrow' => 'About the association',
            'heading' => 'A connected home for professional development.',
            'summary' => 'The platform is designed to support membership, learning, professional engagement and trusted public services.',
        ],
        'vision' => [
            'title' => 'Vision & Mission',
            'description' => 'The official vision and mission page for AIMS Nigeria.',
            'eyebrow' => 'Institutional direction',
            'heading' => 'Vision and mission, presented with clarity.',
            'summary' => 'Approved institutional statements will be published here once supplied and verified by the organisation.',
        ],
        'leadership' => [
            'title' => 'Leadership',
            'description' => 'Explore the governance and leadership structure of AIMS Nigeria.',
            'eyebrow' => 'Governance and stewardship',
            'heading' => 'Leadership information with accountable structure.',
            'summary' => 'Verified profiles will be published from the organisation data layer rather than embedded directly in page templates.',
        ],
        'membership' => [
            'title' => 'Membership',
            'description' => 'Explore AIMS Nigeria membership grades and the planned application journey.',
            'eyebrow' => 'Professional membership',
            'heading' => 'A clear path into the AIMS Nigeria community.',
            'summary' => 'Review the initial membership grades and understand how the secure application journey will work when enrolment opens.',
        ],
        'programmes' => [
            'title' => 'Professional Programmes',
            'description' => 'Explore the programme pathways planned for the AIMS Nigeria platform.',
            'eyebrow' => 'Learning and advancement',
            'heading' => 'Professional learning paths designed to stay current.',
            'summary' => 'Programme details will remain database-driven so approved offerings, fees and entry requirements can be maintained accurately.',
        ],
        'areas' => [
            'title' => 'Professional Areas',
            'description' => 'Explore the initial professional areas represented within the AIMS Nigeria platform.',
            'eyebrow' => 'Areas of practice',
            'heading' => 'One platform, multiple professional disciplines.',
            'summary' => 'The architecture supports the initial areas below and can accommodate additional disciplines without redesigning the site.',
        ],
        'events' => [
            'title' => 'Events',
            'description' => 'Find official AIMS Nigeria events, conferences, workshops, webinars and induction activities.',
            'eyebrow' => 'Gather, learn and connect',
            'heading' => 'Official events will live in one dependable calendar.',
            'summary' => 'Published event details and registration links will appear here once approved event records are available.',
        ],
        'resources' => [
            'title' => 'Resources',
            'description' => 'Access official AIMS Nigeria publications, downloads, guidance and professional resources.',
            'eyebrow' => 'Knowledge library',
            'heading' => 'Useful resources, clearly organised.',
            'summary' => 'Approved publications and downloads will be surfaced here from the content management system.',
        ],
        'news' => [
            'title' => 'News',
            'description' => 'Read official news and updates from AIMS Nigeria.',
            'eyebrow' => 'Official updates',
            'heading' => 'News with a clear source and publication record.',
            'summary' => 'Only reviewed and published articles will appear in this space.',
        ],
        'contact' => [
            'title' => 'Contact',
            'description' => 'Find verified contact channels for AIMS Nigeria.',
            'eyebrow' => 'Get in touch',
            'heading' => 'Connect through an official channel.',
            'summary' => 'Verified contact details will be displayed from organisation settings as soon as they are configured.',
        ],
        'verify' => [
            'title' => 'Verification',
            'description' => 'AIMS Nigeria membership and certificate verification landing page.',
            'eyebrow' => 'Public verification',
            'heading' => 'A trusted starting point for verification.',
            'summary' => 'Confirm issued membership and certificate records through the secure public verification service.',
        ],
    ],
    'membership_grades' => ['Fellow', 'Member', 'Associate'],
    'leadership_groups' => ['Advisory Board', 'Governing Board', 'Management Team', 'Programme Coordinators'],
];
