<?php declare(strict_types=1); $status=(string)$application['status']; ?>
<section class="section"><div class="container-narrow"><a class="text-link" href="/admin/programme-applications">← Back to applications</a><div class="section-heading"><p class="eyebrow"><?= $e($application['application_reference']??'Programme application') ?></p><h1><?= $e($application['programme_code'].' — '.$application['programme_name']) ?></h1><p><?= $e($application['email']) ?> · <?= $e(ucwords($status)) ?></p></div>
<?php if($message):?><div class="notice" role="status"><?= $e($message) ?></div><?php endif;?><?php if($error):?><div class="form-error" role="alert"><?= $e($error) ?></div><?php endif;?>
<dl class="detail-list"><div><dt>Programme type</dt><dd><?= $e($application['programme_type']) ?></dd></div><div><dt>Highest qualification</dt><dd><?= $e($application['highest_qualification']?:'Not supplied') ?></dd></div><div><dt>Current organisation</dt><dd><?= $e($application['current_organisation']?:'Not supplied') ?></dd></div><div><dt>Professional background</dt><dd><?= nl2br($e($application['professional_background']?:'Not supplied')) ?></dd></div><div><dt>Motivation</dt><dd><?= nl2br($e($application['motivation']?:'Not supplied')) ?></dd></div><div><dt>Declaration</dt><dd><?= $e($application['declaration_name']?:'Not supplied') ?></dd></div><?php if($application['review_note']):?><div><dt>Review note</dt><dd><?= $e($application['review_note']) ?></dd></div><?php endif;?><?php if($application['decision_note']):?><div><dt>Decision note</dt><dd><?= $e($application['decision_note']) ?></dd></div><?php endif;?><?php if($application['enrolment_number']):?><div><dt>Enrolment number</dt><dd><?= $e($application['enrolment_number']) ?></dd></div><?php endif;?></dl>
<div class="admin-actions"><?php if($status==='submitted'):?><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/review"><?= $csrf->field() ?><label>Review note<textarea name="note" maxlength="5000"></textarea></label><button class="btn btn-navy" type="submit">Start review</button></form><?php endif;?>
<?php if(in_array($status,['submitted','review'],true)):?><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/reject"><?= $csrf->field() ?><label>Rejection reason<textarea name="note" minlength="3" maxlength="5000" required></textarea></label><button class="btn btn-outline" type="submit">Reject</button></form><?php endif;?>
<?php if($status==='review'):?><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/approve"><?= $csrf->field() ?><label>Decision note<textarea name="note" maxlength="5000"></textarea></label><button class="btn btn-navy" type="submit">Approve application</button></form><?php endif;?>
<?php if($status==='approved'):?><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/enrol"><?= $csrf->field() ?><button class="btn btn-navy" type="submit">Create enrolment</button></form><?php endif;?>
<?php if($status==='enrolled'):?><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/complete"><?= $csrf->field() ?><button class="btn btn-navy" type="submit">Mark completed</button></form><form method="post" action="/admin/programme-applications/<?= rawurlencode($application['public_id']) ?>/withdraw-enrolment"><?= $csrf->field() ?><label>Withdrawal reason<textarea name="note" minlength="3" maxlength="5000" required></textarea></label><button class="btn btn-outline" type="submit">Withdraw enrolment</button></form><?php endif;?></div>
</div></section>
