<?php

declare(strict_types=1);

namespace App\Services\Renewals;

use App\Authorization\PermissionCheckerInterface;
use App\Services\Payments\VerifiedPaymentListenerInterface;
use DateTimeImmutable;
use DomainException;

final class MembershipRenewalService implements VerifiedPaymentListenerInterface
{
    public function __construct(private readonly RenewalRepositoryInterface $repository,private readonly PermissionCheckerInterface $permissions) {}
    public function dashboard(int $userId):RenewalResult{return $userId>0?RenewalResult::success('Renewal details loaded.',$this->repository->dashboardForUser($userId)):RenewalResult::failure(403,'Member access is required.');}
    public function generate(int $userId):RenewalResult{if($userId<1)return RenewalResult::failure(403,'Member access is required.');try{return RenewalResult::success('Renewal invoice is ready.',$this->repository->generateForUser($userId,new DateTimeImmutable('now')));}catch(DomainException$e){return RenewalResult::failure(409,$e->getMessage());}}
    public function paymentVerified(string $invoicePublicId):void{if(!$this->uuid($invoicePublicId))throw new DomainException('Verified invoice reference is invalid.');$this->repository->applyVerifiedInvoice($invoicePublicId,new DateTimeImmutable('now'));}
    public function expireDue():int{return$this->repository->expireDue(new DateTimeImmutable('now'));}
    public function adminIndex(int $actor):RenewalResult{if(!$this->allowed($actor)&&!$this->policyAllowed($actor))return RenewalResult::failure(403,'You are not authorized to manage renewals.');return RenewalResult::success('Renewals loaded.',['renewals'=>$this->repository->adminRenewals(),'configuration'=>$this->repository->renewalConfiguration(),'can_override'=>$this->allowed($actor),'can_configure'=>$this->policyAllowed($actor)]);}
    public function savePolicy(int$actor,?string$id,array$input):RenewalResult{if(!$this->policyAllowed($actor))return RenewalResult::failure(403,'You are not authorized to configure renewal policy.');if($id!==null&&!$this->uuid($id))return RenewalResult::failure(404,'Renewal policy not found.');$name=$this->text($input,'name');$grade=$this->text($input,'membership_grade');$fee=$this->text($input,'fee_setting');$unit=$this->text($input,'period_unit');$rule=$this->text($input,'start_rule');$value=filter_var($input['period_value']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1200]]);$window=filter_var($input['renewal_window_days']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>3650]]);$grace=filter_var($input['grace_days']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>3650]]);$from=$this->date($input['effective_from']??null);$until=$this->date($input['effective_until']??null,true);if(mb_strlen($name)<3||mb_strlen($name)>180||!$this->uuid($grade)||!$this->uuid($fee)||$value===false||$window===false||$grace===false||!in_array($unit,['days','months','years'],true)||!in_array($rule,['current_expiry','payment_date'],true)||$from===null||(($input['effective_until']??'')!==''&&$until===null)||($until!==null&&$until<$from))return RenewalResult::failure(422,'Review the renewal policy fields.');try{$publicId=$this->repository->savePolicy($actor,$id,['name'=>$name,'membership_grade'=>$grade,'fee_setting'=>$fee,'period_value'=>$value,'period_unit'=>$unit,'start_rule'=>$rule,'renewal_window_days'=>$window,'grace_days'=>$grace,'effective_from'=>$from,'effective_until'=>$until,'active'=>(string)($input['active']??'1')==='1'?1:0],new DateTimeImmutable('now'));return RenewalResult::success($id===null?'Renewal policy created.':'Renewal policy updated.',['public_id'=>$publicId]);}catch(DomainException$e){return RenewalResult::failure(409,$e->getMessage());}}
    public function override(int$actor,string$id,array$input):RenewalResult{if(!$this->allowed($actor))return RenewalResult::failure(403,'You are not authorized to override renewals.');if(!$this->uuid($id))return RenewalResult::failure(404,'Renewal not found.');$action=is_string($input['action']??null)?trim($input['action']):'';$reason=is_string($input['reason']??null)?trim($input['reason']):'';if(!in_array($action,['renew','expire'],true)||mb_strlen($reason)<10||mb_strlen($reason)>500)return RenewalResult::failure(422,'Select a valid override action and provide a reason of 10 to 500 characters.');try{return RenewalResult::success('Administrative renewal override recorded.',$this->repository->override($actor,$id,$action,$reason,new DateTimeImmutable('now')));}catch(DomainException$e){return RenewalResult::failure(409,$e->getMessage());}}
    private function allowed(int$actor):bool{return$actor>0&&$this->permissions->allows($actor,'member.renewal_override');}private function policyAllowed(int$actor):bool{return$actor>0&&$this->permissions->allows($actor,'member.renewal_policy');}private function uuid(string$id):bool{return preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/Di',$id)===1;}private function text(array$input,string$key):string{return is_string($input[$key]??null)?trim($input[$key]):'';}private function date(mixed$value,bool$nullable=false):?string{$value=is_string($value)?trim($value):'';if($nullable&&$value==='')return null;$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value);return$date&&$date->format('Y-m-d')===$value?$value:null;}
}
