<?php declare(strict_types=1); $types=$catalogue['types']??[]; $areas=$catalogue['areas']??[]; $programmes=$catalogue['programmes']??[]; ?>
<section class="section"><div class="container-wide"><div class="section-heading"><p class="eyebrow">Restricted administration</p><h1>Programme catalogue</h1><p>Draft, publish and archive verified programme information. Publishing makes a programme public immediately.</p></div>
<p><a class="btn btn-outline-navy" href="/admin/programme-applications">Review programme applications</a></p>
<?php if ($message): ?><div class="notice" role="status"><?= $e($message) ?></div><?php endif; ?><?php if ($error): ?><div class="form-error" role="alert"><?= $e($error) ?></div><?php endif; ?>
<?php if ($can['create']): ?><details class="admin-panel"><summary>Create programme</summary><form method="post" action="/admin/programmes" class="form-grid"><?php $programme=[]; $submitLabel='Create programme'; include __DIR__.'/programme-form.php'; ?></form></details><?php endif; ?>
<div class="admin-list"><h2>Programmes</h2><?php if ($programmes===[]): ?><p>No programme records exist.</p><?php endif; ?><?php foreach ($programmes as $programme): ?><details class="admin-panel"><summary><?= $e($programme['code'].' — '.$programme['name'].' ('.$programme['status'].')') ?></summary><?php if ($can['update']): ?><form method="post" action="/admin/programmes/<?= rawurlencode($programme['public_id']) ?>" class="form-grid"><?php $submitLabel='Save programme'; include __DIR__.'/programme-form.php'; ?></form><?php endif; ?><?php if ($can['delete']): ?><form method="post" action="/admin/programmes/<?= rawurlencode($programme['public_id']) ?>/archive"><?= $csrf->field() ?><button class="btn btn-outline" type="submit">Archive programme</button></form><?php endif; ?></details><?php endforeach; ?></div>
<?php if ($can['create']): ?><details class="admin-panel"><summary>Create professional area</summary><form method="post" action="/admin/professional-areas" class="form-grid"><?php $area=[]; $submitLabel='Create area'; include __DIR__.'/area-form.php'; ?></form></details><?php endif; ?>
<div class="admin-list"><h2>Professional areas</h2><?php foreach ($areas as $area): ?><details class="admin-panel"><summary><?= $e($area['name'].((int)$area['active']===1?'':' (inactive)')) ?></summary><?php if ($can['update']): ?><form method="post" action="/admin/professional-areas/<?= rawurlencode($area['public_id']) ?>" class="form-grid"><?php $submitLabel='Save area'; include __DIR__.'/area-form.php'; ?></form><?php endif; ?><?php if ($can['delete']): ?><form method="post" action="/admin/professional-areas/<?= rawurlencode($area['public_id']) ?>/archive"><?= $csrf->field() ?><button class="btn btn-outline" type="submit">Archive area</button></form><?php endif; ?></details><?php endforeach; ?></div>
<?php if ($can['assign']): ?><details class="admin-panel"><summary>Assign programme coordinator</summary><form method="post" action="/admin/programmes/coordinators" class="form-grid"><?= $csrf->field() ?><label>Coordinator<select name="person" required><option value="">Select coordinator</option><?php foreach ($catalogue['coordinators'] as $person): ?><option value="<?= $e($person['public_id']) ?>"><?= $e(trim(($person['title']?$person['title'].' ':'').$person['full_name'])) ?></option><?php endforeach; ?></select></label><label>Programme<select name="programme"><option value="">No programme</option><?php foreach ($programmes as $item): ?><option value="<?= $e($item['public_id']) ?>"><?= $e($item['name']) ?></option><?php endforeach; ?></select></label><label>Professional area<select name="area"><option value="">No area</option><?php foreach ($areas as $item): if(!(int)$item['active'])continue; ?><option value="<?= $e($item['public_id']) ?>"><?= $e($item['name']) ?></option><?php endforeach; ?></select></label><label>Role title<input name="role_title" maxlength="160"></label><label>Starts<input type="date" name="starts_at"></label><label>Ends<input type="date" name="ends_at"></label><button class="btn btn-navy" type="submit">Assign coordinator</button></form></details><?php endif; ?>
<div class="admin-list"><h2>Coordinator assignments</h2><?php if (($catalogue['assignments']??[])===[]): ?><p>No active coordinator assignments.</p><?php endif; ?><?php foreach ($catalogue['assignments']??[] as $assignment): ?><div class="admin-panel"><strong><?= $e(trim(($assignment['title']?$assignment['title'].' ':'').$assignment['full_name'])) ?></strong><p><?= $e($assignment['role_title']?:'Coordinator') ?> · <?= $e($assignment['programme_name']?:$assignment['area_name']) ?></p><?php if ($can['assign']): ?><form method="post" action="/admin/programmes/coordinators/<?= rawurlencode($assignment['public_id']) ?>/remove"><?= $csrf->field() ?><button class="btn btn-outline" type="submit">Remove assignment</button></form><?php endif; ?></div><?php endforeach; ?></div>
</div></section>
