<?php

declare(strict_types=1);

namespace App\Services\Certificates;

use App\Authorization\PermissionCheckerInterface;
use App\Security\CertificateTokenSigner;
use App\Security\Security;
use DateTimeImmutable;
use DomainException;
use Throwable;

final class CertificateService
{
    public function __construct(private readonly CertificateRepositoryInterface$repository,private readonly PermissionCheckerInterface$permissions,private readonly CertificateTokenSigner$signer,private readonly string$numberPrefix,private readonly string$verificationUrl=''){}
    public function verify(array$input,string$ip,string$userAgent):CertificateResult{$type=is_string($input['type']??null)?trim($input['type']):'';$value=is_string($input['value']??null)?trim($input['value']):'';if(!in_array($type,['membership_number','certificate_number','qr_token'],true)||$value===''||strlen($value)>500)return CertificateResult::failure(422,'Select a verification type and enter a valid reference.');$hash=hash('sha256',strtolower($value));$now=new DateTimeImmutable('now');try{if($type==='membership_number'){$record=$this->repository->verifyMembership($value,$hash,$ip,$userAgent,$now);return CertificateResult::success($record?'Membership record found.':'No matching public membership record was found.',['found'=>$record!==null,'record'=>$record]);}$publicId=$type==='qr_token'?$this->signer->publicId($value):null;if($type==='qr_token'&&$publicId===null)return CertificateResult::success('No matching public certificate record was found.',['found'=>false,'record'=>null]);$record=$this->repository->verifyCertificate($type,$value,$publicId,$type==='qr_token'?$this->signer->digest($value):'',$hash,$ip,$userAgent,$now);return CertificateResult::success($record?'Certificate record found.':'No matching public certificate record was found.',['found'=>$record!==null,'record'=>$record]);}catch(Throwable){return CertificateResult::failure(503,'Verification is temporarily unavailable.');}}
    public function adminCatalogue(int$actor):CertificateResult{if(!$this->allows($actor,'certificate.issue')&&!$this->allows($actor,'certificate.revoke'))return CertificateResult::failure(403,'You are not authorized to manage certificates.');return CertificateResult::success('Certificates loaded.',$this->repository->adminCatalogue());}
    public function saveType(int$actor,?string$id,array$input):CertificateResult{if(!$this->allows($actor,'certificate.type_manage'))return CertificateResult::failure(403,'You are not authorized to configure certificate types.');if($id!==null&&!$this->uuid($id))return CertificateResult::failure(404,'Certificate type not found.');$code=strtoupper($this->text($input,'code'));$name=$this->text($input,'name');$unit=$this->nullable($input,'validity_unit');$value=($input['validity_value']??'')===''?null:filter_var($input['validity_value'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1200]]);$template=$this->nullable($input,'template_key');if(preg_match('/^[A-Z0-9_-]{2,60}$/D',$code)!==1||mb_strlen($name)<3||mb_strlen($name)>180||(($value===null)!==($unit===null))||($value===false)||($unit!==null&&!in_array($unit,['days','months','years'],true))||($template!==null&&preg_match('/^[a-z0-9._-]{1,100}$/D',$template)!==1))return CertificateResult::failure(422,'Review the certificate type fields.');try{$publicId=$this->repository->saveType($actor,$id,['code'=>$code,'name'=>$name,'description'=>$this->nullable($input,'description'),'validity_value'=>$value,'validity_unit'=>$unit,'template_key'=>$template,'active'=>(string)($input['active']??'1')==='1'?1:0],new DateTimeImmutable('now'));return CertificateResult::success($id===null?'Certificate type created.':'Certificate type updated.',['public_id'=>$publicId]);}catch(DomainException$e){return CertificateResult::failure(409,$e->getMessage());}}
    public function issue(int$actor,array$input):CertificateResult{if(!$this->allows($actor,'certificate.issue'))return CertificateResult::failure(403,'You are not authorized to issue certificates.');if(!$this->signer->available())return CertificateResult::failure(503,'Certificate signing is not configured.');$type=$this->text($input,'certificate_type');$holderType=$this->text($input,'holder_type');$holder=$this->text($input,'holder');$programme=$this->nullable($input,'programme');$event=$this->nullable($input,'event');$issue=$this->date($input['issue_date']??null);$expiry=$this->date($input['expiry_date']??null,true);if(!$this->uuid($type)||!in_array($holderType,['member','person'],true)||!$this->uuid($holder)||$issue===null||(($input['expiry_date']??'')!==''&&$expiry===null)||($expiry!==null&&$expiry<$issue)||($programme!==null&&!$this->uuid($programme))||($event!==null&&!$this->uuid($event)))return CertificateResult::failure(422,'Review the certificate details.');$publicId=Security::uuidV4();$token=$this->signer->issue($publicId);$prefix=preg_match('/^[A-Z0-9-]{2,30}$/D',$this->numberPrefix)===1?$this->numberPrefix:'AIMS-CERT';$number=$prefix.'-'.date('Y').'-'.strtoupper(bin2hex(random_bytes(6)));try{$record=$this->repository->issue($actor,['certificate_type'=>$type,'holder_type'=>$holderType,'holder'=>$holder,'programme'=>$programme,'event'=>$event,'issue_date'=>$issue,'expiry_date'=>$expiry],$publicId,$number,$this->signer->digest($token),new DateTimeImmutable('now'));$record['verification_token']=$token;$record['verification_url']=$this->verificationUrl!==''?rtrim($this->verificationUrl,'?&').'?token='.rawurlencode($token):null;return CertificateResult::success('Certificate issued. Save the verification token in the generated certificate artifact.',$record);}catch(DomainException$e){return CertificateResult::failure(409,$e->getMessage());}}
    public function revoke(int$actor,string$id,array$input):CertificateResult{if(!$this->allows($actor,'certificate.revoke'))return CertificateResult::failure(403,'You are not authorized to revoke certificates.');$reason=$this->text($input,'reason');if(!$this->uuid($id)||mb_strlen($reason)<10||mb_strlen($reason)>500)return CertificateResult::failure(422,'A valid certificate and revocation reason are required.');try{return CertificateResult::success('Certificate revoked.',$this->repository->revoke($actor,$id,$reason,new DateTimeImmutable('now')));}catch(DomainException$e){return CertificateResult::failure(409,$e->getMessage());}}
    public function memberCertificates(int$user):CertificateResult{return$user>0?CertificateResult::success('Certificates loaded.',['certificates'=>$this->repository->certificatesForUser($user)]):CertificateResult::failure(403,'Authentication is required.');}
    private function allows(int$a,string$p):bool{return$a>0&&$this->permissions->allows($a,$p);}private function text(array$i,string$k):string{return is_string($i[$k]??null)?trim($i[$k]):'';}private function nullable(array$i,string$k):?string{$v=$this->text($i,$k);return$v===''?null:$v;}private function uuid(string$v):bool{return preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/Di',$v)===1;}private function date(mixed$v,bool$n=false):?string{$v=is_string($v)?trim($v):'';if($n&&$v==='')return null;$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);return$d&&$d->format('Y-m-d')===$v?$v:null;}
}
