<?php

declare(strict_types=1);

namespace App\Controllers\Cms;

use App\Controllers\Controller;use App\Http\Request;use App\Http\Response;use App\Security\Csrf;use App\Security\Security;use App\Security\SessionManager;use App\Services\Cms\CmsResult;use App\Services\Cms\CmsService;use App\Services\PublicSite\PublicContent;use App\View\View;
final class CmsController extends Controller
{
 public function __construct(View$v,Csrf$c,private readonly CmsService$service,private readonly SessionManager$session,private readonly PublicContent$content){parent::__construct($v,$c);}
 public function news(Request$r):Response{return$this->listing($r,'news','News','Official news and updates.');}public function announcements(Request$r):Response{return$this->listing($r,'announcement','Announcements','Official association announcements.');}
 public function newsPost(Request$r):Response{return$this->postFor('news',$r);}public function announcementPost(Request$r):Response{return$this->postFor('announcement',$r);}public function resourcePost(Request$r):Response{return$this->postFor('resource',$r);}private function postFor(string$type,Request$r):Response{$post=$this->service->post($type,(string)$r->route('slug',''));if(!$post)return Response::html('<h1>404 Not Found</h1>',404);$page=['title'=>$post['title'],'meta_title'=>$post['meta_title']?:$post['title'].' | AIMS Nigeria','description'=>$post['meta_description']?:$post['excerpt']?:'Official AIMS Nigeria content.','eyebrow'=>ucfirst($type),'heading'=>$post['title'],'summary'=>$post['excerpt']?:'Published '.$post['published_at']];return$this->publicView('cms.post',$page,$r,['post'=>$post]);}
 public function page(Request$r):Response{$pageRecord=$this->service->page((string)$r->route('slug',''));if(!$pageRecord)return Response::html('<h1>404 Not Found</h1>',404);$page=['title'=>$pageRecord['title'],'meta_title'=>$pageRecord['meta_title']?:$pageRecord['title'].' | AIMS Nigeria','description'=>$pageRecord['meta_description']?:$pageRecord['summary']?:'Official AIMS Nigeria page.','eyebrow'=>'AIMS Nigeria','heading'=>$pageRecord['title'],'summary'=>$pageRecord['summary']?:'Official published information.'];return$this->publicView('cms.page',$page,$r,['contentPage'=>$pageRecord]);}
 public function resources(Request$r):Response{$library=$this->service->library();return$this->publicView('cms.resources',$this->content->page('resources'),$r,['library'=>$library]);}public function downloads(Request$r):Response{$library=$this->service->library();return$this->publicView('cms.downloads',['title'=>'Downloads','meta_title'=>'Downloads | AIMS Nigeria','description'=>'Official AIMS Nigeria downloads.','eyebrow'=>'Resource library','heading'=>'Official downloads','summary'=>'Published files from AIMS Nigeria.'],$r,['downloads'=>$library['downloads']]);}public function faqs(Request$r):Response{$library=$this->service->library();return$this->publicView('cms.faqs',['title'=>'Frequently Asked Questions','meta_title'=>'FAQs | AIMS Nigeria','description'=>'Answers to frequently asked questions about AIMS Nigeria.','eyebrow'=>'Help and guidance','heading'=>'Frequently asked questions','summary'=>'Published answers to common questions.'],$r,['faqs'=>$library['faqs']]);}
 public function media(Request$r):Response{$m=$this->service->media((string)$r->route('media',''));return$this->file($m,false);}public function download(Request$r):Response{$m=$this->service->download((string)$r->route('slug',''));return$this->file($m,true);}
 public function admin(Request$r):Response{$result=$this->service->admin($this->actor($r));if(!$result->successful)return Response::html('<h1>403 Forbidden</h1>',403);return$this->publicView('cms.admin',['title'=>'Content management','meta_title'=>'Content management | AIMS Nigeria','description'=>'Authorized website content administration.','eyebrow'=>'Administration','heading'=>'Content management','summary'=>'Draft, review, publish and archive official content.'],$r,['cms'=>$result->data,'message'=>$this->session->pullFlash('cms_message'),'error'=>$this->session->pullFlash('cms_error')],true);}
 public function savePage(Request$r):Response{return$this->action($this->service->savePage($this->actor($r),$this->optionalRoute($r,'page'),$r->all()));}public function savePost(Request$r):Response{return$this->action($this->service->savePost($this->actor($r),$this->optionalRoute($r,'post'),$r->all()));}public function saveFaq(Request$r):Response{return$this->action($this->service->saveFaq($this->actor($r),$this->optionalRoute($r,'faq'),$r->all()));}public function saveDownload(Request$r):Response{return$this->action($this->service->saveDownload($this->actor($r),$this->optionalRoute($r,'download'),$r->all()));}public function upload(Request$r):Response{$files=$r->files();return$this->action($this->service->upload($this->actor($r),is_array($files['media']??null)?$files['media']:[],$r->all()));}
 public function mediaStatus(Request$r):Response{return$this->action($this->service->mediaStatus($this->actor($r),(string)$r->route('media',''),$r->all()));}
 private function listing(Request$r,string$type,string$title,string$description):Response{return$this->publicView('cms.listing',['title'=>$title,'meta_title'=>$title.' | AIMS Nigeria','description'=>$description,'eyebrow'=>'Official updates','heading'=>$title,'summary'=>$description],$r,['posts'=>$this->service->posts($type),'postType'=>$type]);}private function file(?array$m,bool$attachment):Response{if(!$m)return Response::html('<h1>404 Not Found</h1>',404);try{$body=$this->service->readMedia($m);}catch(\Throwable){return Response::html('<h1>404 Not Found</h1>',404);}$name=preg_replace('/[^A-Za-z0-9._-]+/','-',basename((string)$m['original_name']))?:'download';return(new Response($body,200,['Content-Type'=>(string)$m['mime_type'],'Content-Length'=>(string)strlen($body),'Content-Disposition'=>($attachment?'attachment':'inline').'; filename="'.$name.'"','X-Content-Type-Options'=>'nosniff','Cache-Control'=>'public, max-age=300']));}private function action(CmsResult$r):Response{$this->session->flash($r->successful?'cms_message':'cms_error',$r->message);return Response::redirect('/admin/cms',303)->withHeader('Cache-Control','no-store');}private function optionalRoute(Request$r,string$k):?string{$v=$r->route($k);return is_string($v)&&$v!==''?$v:null;}private function actor(Request$r):int{$u=$r->attribute('auth.user');return is_array($u)?(int)($u['id']??0):0;}private function publicView(string$template,array$page,Request$r,array$data=[],bool$private=false):Response{$response=$this->view($template,array_merge(['site'=>$this->content->site(),'navigation'=>$this->content->navigation(),'page'=>$page,'activePage'=>'cms','requestPath'=>$r->path(),'e'=>[Security::class,'escape']],$data),'layouts.public');return$private?$response->withHeader('Cache-Control','no-store, private'):$response;}
}
