<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Database\Connection;
use App\Security\Security;
use App\Services\Certificates\CertificateRepositoryInterface;
use DateTimeImmutable;
use DomainException;
use PDO;
use PDOException;

final class CertificateRepository extends Repository implements CertificateRepositoryInterface
{
    public function __construct(Connection$database){parent::__construct($database);}
    public function verifyMembership(string$number,string$lookupHash,string$ip,string$userAgent,DateTimeImmutable$now):?array{return$this->database->transaction(function(PDO$db)use($number,$lookupHash,$ip,$userAgent,$now):?array{$s=$db->prepare("SELECT members.membership_number,members.status,members.joined_at,members.expires_at,grades.name AS membership_grade,COALESCE(NULLIF(profiles.preferred_name,''),NULLIF(CONCAT_WS(' ',JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.first_name')),JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.last_name'))),''),'Member') AS holder_name FROM members INNER JOIN membership_grades grades ON grades.id=members.membership_grade_id INNER JOIN membership_applications applications ON applications.id=members.approved_application_id LEFT JOIN member_profiles profiles ON profiles.member_id=members.id WHERE members.membership_number=:number LIMIT 1");$s->execute(['number'=>$number]);$row=$s->fetch();$safe=is_array($row)?$this->safeMembership($row,$now):null;$this->logVerification($db,null,'membership_number',$lookupHash,$safe===null?'not_found':($safe['status']==='expired'?'expired':'valid'),$ip,$userAgent,$now);return$safe;});}
    public function verifyCertificate(string$method,string$value,?string$publicId,string$tokenHash,string$lookupHash,string$ip,string$userAgent,DateTimeImmutable$now):?array{return$this->database->transaction(function(PDO$db)use($method,$value,$publicId,$tokenHash,$lookupHash,$ip,$userAgent,$now):?array{$where=$method==='qr_token'?'certificates.public_id=:public_id AND certificates.verification_token_hash=:token_hash':'certificates.certificate_number=:number';$s=$db->prepare("SELECT certificates.id,certificates.certificate_number,certificates.issue_date,certificates.expiry_date,certificates.status,certificates.revoked_at,types.name AS certificate_type,COALESCE(NULLIF(profiles.preferred_name,''),NULLIF(CONCAT_WS(' ',JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.first_name')),JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.last_name'))),''),people.full_name,'Certificate holder') AS holder_name,programmes.name AS programme_name,events.title AS event_title FROM certificates INNER JOIN certificate_types types ON types.id=certificates.certificate_type_id LEFT JOIN members ON members.id=certificates.member_id LEFT JOIN membership_applications applications ON applications.id=members.approved_application_id LEFT JOIN member_profiles profiles ON profiles.member_id=members.id LEFT JOIN people ON people.id=certificates.person_id LEFT JOIN programmes ON programmes.id=certificates.programme_id LEFT JOIN events ON events.id=certificates.event_id WHERE {$where} LIMIT 1");$s->execute($method==='qr_token'?['public_id'=>$publicId,'token_hash'=>$tokenHash]:['number'=>$value]);$row=$s->fetch();$safe=is_array($row)?$this->safeCertificate($row,$now):null;$this->logVerification($db,is_array($row)?(int)$row['id']:null,$method,$lookupHash,$safe['status']??'not_found',$ip,$userAgent,$now);return$safe;});}
    public function adminCatalogue():array{$db=$this->connection();return['types'=>$db->query("SELECT public_id,code,name,validity_value,validity_unit,active FROM certificate_types ORDER BY name")->fetchAll(),'members'=>$db->query("SELECT members.public_id,members.membership_number,COALESCE(NULLIF(profiles.preferred_name,''),NULLIF(CONCAT_WS(' ',JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.first_name')),JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.last_name'))),''),'Member') AS holder_name FROM members INNER JOIN membership_applications applications ON applications.id=members.approved_application_id LEFT JOIN member_profiles profiles ON profiles.member_id=members.id WHERE members.status IN ('active','lapsed') ORDER BY holder_name")->fetchAll(),'people'=>$db->query("SELECT public_id,full_name FROM people WHERE active=1 AND deleted_at IS NULL ORDER BY full_name")->fetchAll(),'programmes'=>$db->query("SELECT public_id,code,name FROM programmes WHERE status='published' AND deleted_at IS NULL ORDER BY name")->fetchAll(),'events'=>$db->query("SELECT public_id,title,event_date FROM events WHERE status IN ('published','completed') AND deleted_at IS NULL ORDER BY event_date DESC")->fetchAll(),'certificates'=>$db->query("SELECT certificates.public_id,certificates.certificate_number,certificates.issue_date,certificates.expiry_date,certificates.status,types.name AS certificate_type,COALESCE(members.membership_number,people.full_name) AS holder_reference FROM certificates INNER JOIN certificate_types types ON types.id=certificates.certificate_type_id LEFT JOIN members ON members.id=certificates.member_id LEFT JOIN people ON people.id=certificates.person_id ORDER BY certificates.issue_date DESC,certificates.id DESC LIMIT 250")->fetchAll()];}
    public function saveType(int$actor,?string$publicId,array$data,DateTimeImmutable$now):string{try{return$this->database->transaction(function(PDO$db)use($actor,$publicId,$data,$now):string{$created=$publicId===null;$publicId??=Security::uuidV4();$values=['public_id'=>$publicId,'code'=>$data['code'],'name'=>$data['name'],'description'=>$data['description'],'value'=>$data['validity_value'],'unit'=>$data['validity_unit'],'template'=>$data['template_key'],'active'=>$data['active'],'actor'=>$actor,'now'=>$this->stamp($now)];if($created)$db->prepare('INSERT INTO certificate_types (public_id,code,name,description,validity_value,validity_unit,template_key,active,created_by_user_id,created_at,updated_at) VALUES (:public_id,:code,:name,:description,:value,:unit,:template,:active,:actor,:now,:now)')->execute($values);else{$update=$db->prepare('UPDATE certificate_types SET code=:code,name=:name,description=:description,validity_value=:value,validity_unit=:unit,template_key=:template,active=:active,updated_at=:now WHERE public_id=:public_id');unset($values['actor']);$update->execute($values);if($update->rowCount()===0){$exists=$db->prepare('SELECT id FROM certificate_types WHERE public_id=:id');$exists->execute(['id'=>$publicId]);if($exists->fetchColumn()===false)throw new DomainException('Certificate type not found.');}}$db->prepare("INSERT INTO audit_logs (actor_user_id,action,auditable_type,auditable_id,description,new_values,request_id,created_at) VALUES (:actor,:action,'certificate_type',:id,'A certificate type was configured.',:values,:request,:now)")->execute(['actor'=>$actor,'action'=>$created?'certificate.type_created':'certificate.type_updated','id'=>$publicId,'values'=>json_encode($data,JSON_THROW_ON_ERROR),'request'=>bin2hex(random_bytes(16)),'now'=>$this->stamp($now)]);return$publicId;});}catch(PDOException$e){if($e->getCode()==='23000')throw new DomainException('Certificate type code already exists.');throw$e;}}
    public function issue(int$actor,array$data,string$publicId,string$number,string$tokenHash,DateTimeImmutable$now):array{try{return$this->database->transaction(function(PDO$db)use($actor,$data,$publicId,$number,$tokenHash,$now):array{$type=$this->id($db,'certificate_types',$data['certificate_type'],"active=1");$member=$data['holder_type']==='member'?$this->id($db,'members',$data['holder'],"status IN ('active','lapsed')"):null;$person=$data['holder_type']==='person'?$this->id($db,'people',$data['holder'],"active=1 AND deleted_at IS NULL"):null;$programme=$data['programme']!==null?$this->id($db,'programmes',$data['programme'],"deleted_at IS NULL"):null;$event=$data['event']!==null?$this->id($db,'events',$data['event'],"deleted_at IS NULL"):null;if($type===null||($member===null&&$person===null)||($data['programme']!==null&&$programme===null)||($data['event']!==null&&$event===null))throw new DomainException('Certificate type, holder, programme, or event reference is unavailable.');$expiry=$data['expiry_date'];if($expiry===null){$policy=$db->prepare('SELECT validity_value,validity_unit FROM certificate_types WHERE id=:id');$policy->execute(['id'=>$type]);$p=$policy->fetch();if(is_array($p)&&$p['validity_value']!==null)$expiry=$this->addPeriod($data['issue_date'],(int)$p['validity_value'],(string)$p['validity_unit']);}$stamp=$this->stamp($now);$db->prepare("INSERT INTO certificates (public_id,certificate_number,certificate_type_id,member_id,person_id,programme_id,event_id,issued_by_user_id,issue_date,expiry_date,status,verification_token_hash,created_at,updated_at) VALUES (:public_id,:number,:type,:member,:person,:programme,:event,:actor,:issue_date,:expiry_date,'issued',:token_hash,:now,:now)")->execute(['public_id'=>$publicId,'number'=>$number,'type'=>$type,'member'=>$member,'person'=>$person,'programme'=>$programme,'event'=>$event,'actor'=>$actor,'issue_date'=>$data['issue_date'],'expiry_date'=>$expiry,'token_hash'=>$tokenHash,'now'=>$stamp]);$this->audit($db,$actor,'certificate.issued',$publicId,['certificate_number'=>$number,'issue_date'=>$data['issue_date'],'expiry_date'=>$expiry],$now);return['public_id'=>$publicId,'certificate_number'=>$number,'issue_date'=>$data['issue_date'],'expiry_date'=>$expiry,'status'=>'issued'];});}catch(PDOException$e){if($e->getCode()==='23000')throw new DomainException('Certificate number or verification token conflicts with an existing certificate.');throw$e;}}
    public function revoke(int$actor,string$publicId,string$reason,DateTimeImmutable$now):array{return$this->database->transaction(function(PDO$db)use($actor,$publicId,$reason,$now):array{$s=$db->prepare('SELECT id,status,certificate_number FROM certificates WHERE public_id=:id LIMIT 1 FOR UPDATE');$s->execute(['id'=>$publicId]);$c=$s->fetch();if(!is_array($c))throw new DomainException('Certificate not found.');if($c['status']==='revoked')return['public_id'=>$publicId,'status'=>'revoked','idempotent'=>true];$stamp=$this->stamp($now);$db->prepare("UPDATE certificates SET status='revoked',revoked_at=:now,revoked_by_user_id=:actor,revocation_reason=:reason,updated_at=:now WHERE id=:id")->execute(['now'=>$stamp,'actor'=>$actor,'reason'=>$reason,'id'=>$c['id']]);$this->audit($db,$actor,'certificate.revoked',$publicId,['certificate_number'=>$c['certificate_number'],'reason'=>$reason],$now);return['public_id'=>$publicId,'status'=>'revoked','idempotent'=>false];});}
    public function certificatesForUser(int$userId):array{$s=$this->connection()->prepare("SELECT certificates.public_id,certificates.certificate_number,certificates.issue_date,certificates.expiry_date,CASE WHEN certificates.status='revoked' THEN 'revoked' WHEN certificates.expiry_date IS NOT NULL AND certificates.expiry_date<CURRENT_DATE THEN 'expired' ELSE 'issued' END AS status,types.name AS certificate_type,programmes.name AS programme_name,events.title AS event_title FROM certificates INNER JOIN certificate_types types ON types.id=certificates.certificate_type_id INNER JOIN members ON members.id=certificates.member_id LEFT JOIN programmes ON programmes.id=certificates.programme_id LEFT JOIN events ON events.id=certificates.event_id WHERE members.user_id=:user ORDER BY certificates.issue_date DESC,certificates.id DESC");$s->execute(['user'=>$userId]);return$s->fetchAll();}
    private function id(PDO$db,string$table,string$publicId,string$condition):?int{$s=$db->prepare("SELECT id FROM {$table} WHERE public_id=:id AND {$condition} LIMIT 1");$s->execute(['id'=>$publicId]);$id=$s->fetchColumn();return$id===false?null:(int)$id;}private function addPeriod(string$date,int$value,string$unit):string{if(!in_array($unit,['days','months','years'],true)||$value<1)throw new DomainException('Certificate validity policy is invalid.');$d=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$d)throw new DomainException('Certificate issue date is invalid.');return$d->modify("+{$value} {$unit}")->format('Y-m-d');}
    private function safeMembership(array$r,DateTimeImmutable$now):array{$status=(string)$r['status'];if(is_string($r['expires_at'])&&$r['expires_at']<$now->format('Y-m-d'))$status='expired';return['record_type'=>'membership','holder_name'=>$r['holder_name'],'membership_number'=>$r['membership_number'],'membership_grade'=>$r['membership_grade'],'status'=>$status,'joined_at'=>$r['joined_at'],'expires_at'=>$r['expires_at']];}private function safeCertificate(array$r,DateTimeImmutable$now):array{$status=$r['status']==='revoked'?'revoked':(is_string($r['expiry_date'])&&$r['expiry_date']<$now->format('Y-m-d')?'expired':'valid');return['record_type'=>'certificate','holder_name'=>$r['holder_name'],'certificate_number'=>$r['certificate_number'],'certificate_type'=>$r['certificate_type'],'programme_name'=>$r['programme_name'],'event_title'=>$r['event_title'],'issue_date'=>$r['issue_date'],'expiry_date'=>$r['expiry_date'],'status'=>$status,'revoked_at'=>$status==='revoked'?$r['revoked_at']:null];}
    private function logVerification(PDO$db,?int$certificate,string$method,string$hash,string$outcome,string$ip,string$userAgent,DateTimeImmutable$now):void{$db->prepare('INSERT INTO certificate_verifications (public_id,certificate_id,verification_method,lookup_hash,outcome,ip_address,user_agent,verified_at) VALUES (:public_id,:certificate,:method,:hash,:outcome,INET6_ATON(NULLIF(:ip,\'\')),:user_agent,:now)')->execute(['public_id'=>Security::uuidV4(),'certificate'=>$certificate,'method'=>$method,'hash'=>$hash,'outcome'=>$outcome,'ip'=>$ip==='unknown'?'':$ip,'user_agent'=>mb_substr($userAgent,0,1024),'now'=>$this->stamp($now)]);}private function audit(PDO$db,int$actor,string$action,string$id,array$values,DateTimeImmutable$now):void{$db->prepare("INSERT INTO audit_logs (actor_user_id,action,auditable_type,auditable_id,description,new_values,request_id,created_at) VALUES (:actor,:action,'certificate',:id,'A certificate lifecycle action was completed.',:values,:request,:now)")->execute(['actor'=>$actor,'action'=>$action,'id'=>$id,'values'=>json_encode($values,JSON_THROW_ON_ERROR),'request'=>bin2hex(random_bytes(16)),'now'=>$this->stamp($now)]);}private function stamp(DateTimeImmutable$d):string{return$d->format('Y-m-d H:i:s.u');}
}
