<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Database\Connection;
use App\Security\Security;
use App\Services\Renewals\RenewalRepositoryInterface;
use DateTimeImmutable;
use DomainException;
use PDO;
use PDOException;

final class MembershipRenewalRepository extends Repository implements RenewalRepositoryInterface
{
    public function __construct(Connection $database){parent::__construct($database);}

    public function dashboardForUser(int $userId):array
    {
        $member=$this->connection()->prepare("SELECT members.public_id,members.membership_number,members.status,members.expires_at,grades.name AS grade_name FROM members INNER JOIN membership_grades grades ON grades.id=members.membership_grade_id WHERE members.user_id=:user LIMIT 1");$member->execute(['user'=>$userId]);$memberRow=$member->fetch();
        if(!is_array($memberRow))return['member'=>null,'policy'=>null,'renewal'=>null];
        $policy=$this->connection()->prepare("SELECT policies.public_id,policies.name,policies.period_value,policies.period_unit,policies.start_rule,policies.renewal_window_days,policies.grace_days,fees.amount_minor,fees.currency FROM membership_renewal_policies policies INNER JOIN members ON members.membership_grade_id=policies.membership_grade_id AND members.user_id=:user INNER JOIN fee_settings fees ON fees.id=policies.fee_setting_id AND fees.active=1 AND fees.deleted_at IS NULL WHERE policies.active=1 AND policies.effective_from<=CURRENT_DATE AND (policies.effective_until IS NULL OR policies.effective_until>=CURRENT_DATE) ORDER BY policies.effective_from DESC,policies.id DESC LIMIT 1");$policy->execute(['user'=>$userId]);$policyRow=$policy->fetch();
        $renewal=$this->connection()->prepare("SELECT renewals.public_id,renewals.renewal_reference,renewals.status,renewals.previous_expiry_date,renewals.renewed_from_date,renewals.renewed_until_date,renewals.fee_amount_minor,renewals.fee_currency,renewals.due_at,renewals.paid_at,renewals.renewed_at,invoices.public_id AS invoice_public_id,invoices.invoice_number,invoices.status AS invoice_status FROM membership_renewals renewals INNER JOIN members ON members.id=renewals.member_id LEFT JOIN invoices ON invoices.id=renewals.invoice_id WHERE members.user_id=:user ORDER BY renewals.created_at DESC,renewals.id DESC LIMIT 1");$renewal->execute(['user'=>$userId]);$renewalRow=$renewal->fetch();
        return['member'=>$memberRow,'policy'=>is_array($policyRow)?$policyRow:null,'renewal'=>is_array($renewalRow)?$renewalRow:null];
    }

    public function generateForUser(int$userId,DateTimeImmutable$now):array
    {
        try{return$this->database->transaction(function(PDO$db)use($userId,$now):array{
            $member=$db->prepare("SELECT members.id,members.public_id,members.membership_grade_id,members.status,members.expires_at,users.email,COALESCE(NULLIF(CONCAT_WS(' ',JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.first_name')),JSON_UNQUOTE(JSON_EXTRACT(applications.personal_information,'$.last_name'))),''),users.email) AS bill_name FROM members INNER JOIN users ON users.id=members.user_id INNER JOIN membership_applications applications ON applications.id=members.approved_application_id WHERE members.user_id=:user LIMIT 1 FOR UPDATE");$member->execute(['user'=>$userId]);$m=$member->fetch();if(!is_array($m)||!in_array($m['status'],['active','lapsed'],true))throw new DomainException('An active or lapsed membership is required for renewal.');
            $open=$db->prepare("SELECT public_id,renewal_reference,status FROM membership_renewals WHERE member_id=:member AND status NOT IN ('renewed','expired') ORDER BY id DESC LIMIT 1");$open->execute(['member'=>$m['id']]);$existing=$open->fetch();if(is_array($existing)){return['renewal'=>$existing,'idempotent'=>true];}
            $today=$now->setTime(0,0);$policy=$db->prepare("SELECT policies.*,fees.amount_minor,fees.currency,fees.name AS fee_name,fees.fee_type FROM membership_renewal_policies policies INNER JOIN fee_settings fees ON fees.id=policies.fee_setting_id AND fees.active=1 AND fees.deleted_at IS NULL WHERE policies.membership_grade_id=:grade AND policies.active=1 AND policies.effective_from<=:today AND (policies.effective_until IS NULL OR policies.effective_until>=:today) ORDER BY policies.effective_from DESC,policies.id DESC LIMIT 1 FOR UPDATE");$policy->execute(['grade'=>$m['membership_grade_id'],'today'=>$today->format('Y-m-d')]);$p=$policy->fetch();if(!is_array($p)||$p['fee_type']!=='membership_renewal')throw new DomainException('No active renewal policy and fee are configured for this membership grade.');
            $expiry=$m['expires_at']!==null?DateTimeImmutable::createFromFormat('!Y-m-d',(string)$m['expires_at']):false;if($p['start_rule']==='current_expiry'&&$expiry===false)throw new DomainException('This policy requires a current membership expiry date.');if($expiry!==false&&$expiry>$today->modify('+'.(int)$p['renewal_window_days'].' days'))throw new DomainException('This membership is not yet within its configured renewal window.');
            $dueBase=$expiry!==false?$expiry:$today;$due=$dueBase->modify('+'.(int)$p['grace_days'].' days')->setTime(23,59,59);if($due<$now)throw new DomainException('The configured renewal grace period has expired; an authorized review is required.');
            $stamp=$this->stamp($now);$renewalId=Security::uuidV4();$reference='AIMS-REN-'.$now->format('Y').'-'.strtoupper(bin2hex(random_bytes(6)));
            $db->prepare("INSERT INTO membership_renewals (public_id,member_id,renewal_policy_id,renewal_reference,status,previous_expiry_date,period_value,period_unit,start_rule,fee_amount_minor,fee_currency,due_at,created_at,updated_at) VALUES (:public_id,:member,:policy,:reference,'renewal_due',:expiry,:period_value,:period_unit,:start_rule,:amount,:currency,:due,:now,:now)")->execute(['public_id'=>$renewalId,'member'=>$m['id'],'policy'=>$p['id'],'reference'=>$reference,'expiry'=>$m['expires_at'],'period_value'=>$p['period_value'],'period_unit'=>$p['period_unit'],'start_rule'=>$p['start_rule'],'amount'=>$p['amount_minor'],'currency'=>$p['currency'],'due'=>$due->format('Y-m-d H:i:s.u'),'now'=>$stamp]);$renewalDbId=(int)$db->lastInsertId();$this->history($db,$renewalDbId,null,'renewal_due','member','Renewal requested by the member.',$userId,$now);
            $invoiceId=Security::uuidV4();$invoiceNumber='AIMS-INV-'.$now->format('Y').'-'.strtoupper(bin2hex(random_bytes(6)));$db->prepare("INSERT INTO invoices (public_id,invoice_number,user_id,bill_to_name,bill_to_email,source_type,source_public_id,currency,subtotal_minor,total_minor,status,due_at,created_at,updated_at) VALUES (:public_id,:number,:user,:name,:email,'membership_renewal',:source,:currency,:amount,:amount,'pending',:due,:now,:now)")->execute(['public_id'=>$invoiceId,'number'=>$invoiceNumber,'user'=>$userId,'name'=>$m['bill_name'],'email'=>$m['email'],'source'=>$renewalId,'currency'=>$p['currency'],'amount'=>$p['amount_minor'],'due'=>$due->format('Y-m-d H:i:s.u'),'now'=>$stamp]);$invoiceDbId=(int)$db->lastInsertId();$db->prepare("INSERT INTO invoice_items (invoice_id,fee_setting_id,fee_type,description,quantity,unit_amount_minor,line_total_minor,created_at) VALUES (:invoice,:fee,'membership_renewal',:description,1,:amount,:amount,:now)")->execute(['invoice'=>$invoiceDbId,'fee'=>$p['fee_setting_id'],'description'=>$p['fee_name'],'amount'=>$p['amount_minor'],'now'=>$stamp]);
            $db->prepare("UPDATE membership_renewals SET invoice_id=:invoice,status='invoice_generated',updated_at=:now WHERE id=:id")->execute(['invoice'=>$invoiceDbId,'now'=>$stamp,'id'=>$renewalDbId]);$this->history($db,$renewalDbId,'renewal_due','invoice_generated','member','Renewal invoice generated.',$userId,$now);$db->prepare("UPDATE membership_renewals SET status='payment_pending',updated_at=:now WHERE id=:id")->execute(['now'=>$stamp,'id'=>$renewalDbId]);$this->history($db,$renewalDbId,'invoice_generated','payment_pending','member','Awaiting independently verified payment.',$userId,$now);$this->audit($db,$userId,'membership.renewal_invoice_generated',$renewalId,['invoice_public_id'=>$invoiceId,'amount_minor'=>(int)$p['amount_minor'],'currency'=>$p['currency']],$now);
            return['renewal'=>['public_id'=>$renewalId,'renewal_reference'=>$reference,'status'=>'payment_pending'],'invoice'=>['public_id'=>$invoiceId,'invoice_number'=>$invoiceNumber],'idempotent'=>false];
        });}catch(PDOException$e){if($e->getCode()==='23000')throw new DomainException('A renewal or invoice already exists for this membership period.');throw$e;}
    }

    public function applyVerifiedInvoice(string$invoicePublicId,DateTimeImmutable$now):void
    {
        $this->database->transaction(function(PDO$db)use($invoicePublicId,$now):void{
            $s=$db->prepare("SELECT renewals.*,invoices.id AS invoice_db_id,invoices.status AS invoice_status,invoices.total_minor,invoices.currency AS invoice_currency,(SELECT MAX(payments.paid_at) FROM payments WHERE payments.invoice_id=invoices.id AND payments.status='successful' AND payments.verified_at IS NOT NULL AND payments.amount_minor=invoices.total_minor AND payments.currency=invoices.currency) AS verified_paid_at FROM membership_renewals renewals INNER JOIN invoices ON invoices.id=renewals.invoice_id WHERE invoices.public_id=:invoice LIMIT 1 FOR UPDATE");$s->execute(['invoice'=>$invoicePublicId]);$r=$s->fetch();if(!is_array($r))return;if($r['status']==='renewed')return;if($r['status']==='expired')throw new DomainException('An expired renewal requires authorized review.');if($r['invoice_status']!=='paid'||$r['verified_paid_at']===null||(int)$r['total_minor']!==(int)$r['fee_amount_minor']||!hash_equals((string)$r['invoice_currency'],(string)$r['fee_currency']))throw new DomainException('Renewal requires an exact, server-verified invoice payment.');
            $paid=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s.u',(string)$r['verified_paid_at'])?:$now;$stamp=$this->stamp($now);$db->prepare("UPDATE membership_renewals SET status='paid',paid_at=:paid,updated_at=:now WHERE id=:id")->execute(['paid'=>$this->stamp($paid),'now'=>$stamp,'id'=>$r['id']]);$this->history($db,(int)$r['id'],(string)$r['status'],'paid','verified_payment','Exact invoice payment verified server-to-server.',null,$now);
            [$from,$until]=$this->renewalDates($r,$paid);$db->prepare("UPDATE members SET expires_at=:until,status=IF(status='lapsed','active',status),updated_at=:now WHERE id=:member")->execute(['until'=>$until,'now'=>$stamp,'member'=>$r['member_id']]);$db->prepare("UPDATE membership_renewals SET status='renewed',renewed_from_date=:from,renewed_until_date=:until,renewed_at=:now,updated_at=:now WHERE id=:id")->execute(['from'=>$from,'until'=>$until,'now'=>$stamp,'id'=>$r['id']]);$this->history($db,(int)$r['id'],'paid','renewed','verified_payment','Membership validity extended after verified payment.',null,$now);$this->audit($db,null,'membership.renewed_by_verified_payment',(string)$r['public_id'],['invoice_public_id'=>$invoicePublicId,'renewed_from'=>$from,'renewed_until'=>$until],$now);
        });
    }

    public function expireDue(DateTimeImmutable$now):int
    {
        return$this->database->transaction(function(PDO$db)use($now):int{$select=$db->prepare("SELECT id,public_id,member_id,status,invoice_id FROM membership_renewals WHERE status IN ('renewal_due','invoice_generated','payment_pending') AND due_at IS NOT NULL AND due_at<:now ORDER BY id LIMIT 200 FOR UPDATE");$select->execute(['now'=>$this->stamp($now)]);$rows=$select->fetchAll();$stamp=$this->stamp($now);foreach($rows as$r){$db->prepare("UPDATE membership_renewals SET status='expired',expired_at=:now,updated_at=:now WHERE id=:id")->execute(['now'=>$stamp,'id'=>$r['id']]);if($r['invoice_id']!==null)$db->prepare("UPDATE invoices SET status='expired',updated_at=:now WHERE id=:id AND status='pending'")->execute(['now'=>$stamp,'id'=>$r['invoice_id']]);$db->prepare("UPDATE members SET status='lapsed',updated_at=:now WHERE id=:id AND status='active' AND expires_at<CURRENT_DATE")->execute(['now'=>$stamp,'id'=>$r['member_id']]);$this->history($db,(int)$r['id'],(string)$r['status'],'expired','scheduler','Configured renewal deadline expired.',null,$now);$this->audit($db,null,'membership.renewal_expired',(string)$r['public_id'],['from_status'=>$r['status']],$now);}return count($rows);});
    }

    public function renewalConfiguration():array
    {
        $db=$this->connection();return['grades'=>$db->query("SELECT public_id,name FROM membership_grades WHERE active=1 ORDER BY display_order,name")->fetchAll(),'fees'=>$db->query("SELECT public_id,code,name,amount_minor,currency FROM fee_settings WHERE fee_type='membership_renewal' AND active=1 AND deleted_at IS NULL ORDER BY name")->fetchAll(),'policies'=>$db->query("SELECT policies.public_id,policies.name,policies.period_value,policies.period_unit,policies.start_rule,policies.renewal_window_days,policies.grace_days,policies.effective_from,policies.effective_until,policies.active,grades.name AS grade_name,fees.name AS fee_name,fees.amount_minor,fees.currency FROM membership_renewal_policies policies INNER JOIN membership_grades grades ON grades.id=policies.membership_grade_id INNER JOIN fee_settings fees ON fees.id=policies.fee_setting_id ORDER BY policies.effective_from DESC,policies.id DESC")->fetchAll()];
    }

    public function savePolicy(int$actorUserId,?string$policyPublicId,array$policy,DateTimeImmutable$now):string
    {
        return$this->database->transaction(function(PDO$db)use($actorUserId,$policyPublicId,$policy,$now):string{$grade=$db->prepare('SELECT id FROM membership_grades WHERE public_id=:id AND active=1 LIMIT 1');$grade->execute(['id'=>$policy['membership_grade']]);$gradeId=$grade->fetchColumn();$fee=$db->prepare("SELECT id FROM fee_settings WHERE public_id=:id AND fee_type='membership_renewal' AND active=1 AND deleted_at IS NULL LIMIT 1");$fee->execute(['id'=>$policy['fee_setting']]);$feeId=$fee->fetchColumn();if($gradeId===false||$feeId===false)throw new DomainException('Selected membership grade or renewal fee is unavailable.');
            if((int)$policy['active']===1){$overlap=$db->prepare("SELECT id FROM membership_renewal_policies WHERE membership_grade_id=:grade AND active=1 AND (:current_null IS NULL OR public_id<>:current_id) AND effective_from<=COALESCE(:until,'9999-12-31') AND (effective_until IS NULL OR effective_until>=:from) LIMIT 1 FOR UPDATE");$overlap->execute(['grade'=>$gradeId,'current_null'=>$policyPublicId,'current_id'=>$policyPublicId,'until'=>$policy['effective_until'],'from'=>$policy['effective_from']]);if($overlap->fetchColumn()!==false)throw new DomainException('An active policy already overlaps these effective dates for the membership grade.');}
            $stamp=$this->stamp($now);$created=$policyPublicId===null;$policyPublicId??=Security::uuidV4();$values=['name'=>$policy['name'],'grade'=>$gradeId,'fee'=>$feeId,'value'=>$policy['period_value'],'unit'=>$policy['period_unit'],'rule'=>$policy['start_rule'],'window'=>$policy['renewal_window_days'],'grace'=>$policy['grace_days'],'effective_from'=>$policy['effective_from'],'effective_until'=>$policy['effective_until'],'active'=>$policy['active'],'actor'=>$actorUserId,'now'=>$stamp,'public_id'=>$policyPublicId];if($created)$db->prepare('INSERT INTO membership_renewal_policies (public_id,membership_grade_id,fee_setting_id,name,period_value,period_unit,start_rule,renewal_window_days,grace_days,effective_from,effective_until,active,created_by_user_id,created_at,updated_at) VALUES (:public_id,:grade,:fee,:name,:value,:unit,:rule,:window,:grace,:effective_from,:effective_until,:active,:actor,:now,:now)')->execute($values);else{$update=$db->prepare('UPDATE membership_renewal_policies SET membership_grade_id=:grade,fee_setting_id=:fee,name=:name,period_value=:value,period_unit=:unit,start_rule=:rule,renewal_window_days=:window,grace_days=:grace,effective_from=:effective_from,effective_until=:effective_until,active=:active,updated_at=:now WHERE public_id=:public_id');unset($values['actor']);$update->execute($values);if($update->rowCount()===0){$exists=$db->prepare('SELECT id FROM membership_renewal_policies WHERE public_id=:id');$exists->execute(['id'=>$policyPublicId]);if($exists->fetchColumn()===false)throw new DomainException('Renewal policy not found.');}}
            $db->prepare("INSERT INTO audit_logs (actor_user_id,action,auditable_type,auditable_id,description,new_values,request_id,created_at) VALUES (:actor,:action,'membership_renewal_policy',:id,'A renewal policy was configured.',:values,:request,:now)")->execute(['actor'=>$actorUserId,'action'=>$created?'membership.renewal_policy_created':'membership.renewal_policy_updated','id'=>$policyPublicId,'values'=>json_encode(['period_value'=>$policy['period_value'],'period_unit'=>$policy['period_unit'],'start_rule'=>$policy['start_rule'],'renewal_window_days'=>$policy['renewal_window_days'],'grace_days'=>$policy['grace_days'],'effective_from'=>$policy['effective_from'],'effective_until'=>$policy['effective_until'],'active'=>$policy['active']],JSON_THROW_ON_ERROR),'request'=>bin2hex(random_bytes(16)),'now'=>$stamp]);return$policyPublicId;});
    }

    public function adminRenewals():array{return$this->connection()->query("SELECT renewals.public_id,renewals.renewal_reference,renewals.status,renewals.previous_expiry_date,renewals.renewed_until_date,renewals.fee_amount_minor,renewals.fee_currency,renewals.due_at,members.membership_number,users.email,invoices.invoice_number,invoices.status AS invoice_status FROM membership_renewals renewals INNER JOIN members ON members.id=renewals.member_id INNER JOIN users ON users.id=members.user_id LEFT JOIN invoices ON invoices.id=renewals.invoice_id ORDER BY renewals.created_at DESC,renewals.id DESC LIMIT 250")->fetchAll();}

    public function override(int$actor,string$id,string$action,string$reason,DateTimeImmutable$now):array
    {
        return$this->database->transaction(function(PDO$db)use($actor,$id,$action,$reason,$now):array{$s=$db->prepare('SELECT * FROM membership_renewals WHERE public_id=:id LIMIT 1 FOR UPDATE');$s->execute(['id'=>$id]);$r=$s->fetch();if(!is_array($r))throw new DomainException('Renewal not found.');if($r['status']==='renewed'&&$action==='renew'||$r['status']==='expired'&&$action==='expire')return['public_id'=>$id,'status'=>$r['status'],'idempotent'=>true];$stamp=$this->stamp($now);
            if($action==='renew'){[$from,$until]=$this->renewalDates($r,$now);$db->prepare("UPDATE members SET expires_at=:until,status=IF(status='lapsed','active',status),updated_at=:now WHERE id=:member")->execute(['until'=>$until,'now'=>$stamp,'member'=>$r['member_id']]);$db->prepare("UPDATE membership_renewals SET status='renewed',renewed_from_date=:from,renewed_until_date=:until,renewed_at=:now,override_by_user_id=:actor,override_reason=:reason,updated_at=:now WHERE id=:id")->execute(['from'=>$from,'until'=>$until,'now'=>$stamp,'actor'=>$actor,'reason'=>$reason,'id'=>$r['id']]);$to='renewed';}else{$db->prepare("UPDATE members SET status=IF(status='active','lapsed',status),updated_at=:now WHERE id=:member")->execute(['now'=>$stamp,'member'=>$r['member_id']]);$db->prepare("UPDATE membership_renewals SET status='expired',expired_at=:now,override_by_user_id=:actor,override_reason=:reason,updated_at=:now WHERE id=:id")->execute(['now'=>$stamp,'actor'=>$actor,'reason'=>$reason,'id'=>$r['id']]);$to='expired';}
            $this->history($db,(int)$r['id'],(string)$r['status'],$to,'admin_override',$reason,$actor,$now);$this->audit($db,$actor,'membership.renewal_admin_override',$id,['from_status'=>$r['status'],'to_status'=>$to,'reason'=>$reason],$now);return['public_id'=>$id,'status'=>$to,'idempotent'=>false];});
    }

    /** @param array<string,mixed> $r @return array{string,string} */private function renewalDates(array$r,DateTimeImmutable$paid):array{$value=(int)$r['period_value'];$unit=(string)$r['period_unit'];if(!in_array($unit,['days','months','years'],true)||$value<1)throw new DomainException('Renewal policy snapshot is invalid.');if($r['start_rule']==='current_expiry'){if(!is_string($r['previous_expiry_date'])||($base=DateTimeImmutable::createFromFormat('!Y-m-d',$r['previous_expiry_date']))===false)throw new DomainException('Renewal expiry anchor is missing.');$from=$base->modify('+1 day');$until=$base->modify("+{$value} {$unit}");}elseif($r['start_rule']==='payment_date'){$from=$paid->setTime(0,0);$until=$from->modify("+{$value} {$unit}")->modify('-1 day');}else throw new DomainException('Renewal start rule is invalid.');return[$from->format('Y-m-d'),$until->format('Y-m-d')];}
    private function history(PDO$db,int$renewal,?string$from,string$to,string$source,?string$note,?int$actor,DateTimeImmutable$now):void{$db->prepare('INSERT INTO membership_renewal_history (membership_renewal_id,from_status,to_status,transition_source,note,changed_by_user_id,created_at) VALUES (:renewal,:from,:to,:source,:note,:actor,:now)')->execute(['renewal'=>$renewal,'from'=>$from,'to'=>$to,'source'=>$source,'note'=>$note,'actor'=>$actor,'now'=>$this->stamp($now)]);}private function audit(PDO$db,?int$actor,string$action,string$id,array$values,DateTimeImmutable$now):void{$db->prepare("INSERT INTO audit_logs (actor_user_id,action,auditable_type,auditable_id,description,new_values,request_id,created_at) VALUES (:actor,:action,'membership_renewal',:id,'A membership renewal action was completed.',:values,:request,:now)")->execute(['actor'=>$actor,'action'=>$action,'id'=>$id,'values'=>json_encode($values,JSON_THROW_ON_ERROR),'request'=>bin2hex(random_bytes(16)),'now'=>$this->stamp($now)]);}private function stamp(DateTimeImmutable$d):string{return$d->format('Y-m-d H:i:s.u');}
}
